/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuthenticationNewController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('AuthenticationNewController', () => {
  let controller : AuthenticationNewController;

  beforeAll(() => {
    controller = new AuthenticationNewController(testClient);
  });

  it('should Test Refresh authentication token', async () => {
    const response = await makeApiCall(
      () => controller.refreshAuthenticationToken()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test Sign out the current user', async () => {
    const response = await makeApiCall(
      () => controller.signOutTheCurrentUser()
    );

    expect(response.statusCode).toBe(204);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
