/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ExerciseLibraryExerciseCategoriesController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('ExerciseLibraryExerciseCategoriesController', () => {
  let controller : ExerciseLibraryExerciseCategoriesController;

  beforeAll(() => {
    controller = new ExerciseLibraryExerciseCategoriesController(testClient);
  });

  it('should Test getExerciseCategories', async () => {
    const localeCode = 'en-US';

    const response = await makeApiCall(
      () => controller.getExerciseCategories(localeCode)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
