/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { MusclesMuscleGroupsController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('MusclesMuscleGroupsController', () => {
  let controller : MusclesMuscleGroupsController;

  beforeAll(() => {
    controller = new MusclesMuscleGroupsController(testClient);
  });

  it('should Test getMuscleGroups', async () => {
    const localeCode = 'en-US';

    const response = await makeApiCall(
      () => controller.getMuscleGroups(localeCode)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
