/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { MusclesController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('MusclesController', () => {
  let controller : MusclesController;

  beforeAll(() => {
    controller = new MusclesController(testClient);
  });

  it('should Test getMuscles', async () => {
    const localeCode = 'en-US';

    const response = await makeApiCall(
      () => controller.getMuscles(localeCode)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
