/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ProgramsController, SortByEnum, SortOrderEnum } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('ProgramsController', () => {
  let controller : ProgramsController;

  beforeAll(() => {
    controller = new ProgramsController(testClient);
  });

  it('should Test getPrograms', async () => {
    const page = 1;

    const pageSize = 20;

    const sortBy = SortByEnum.CreatedAt;

    const sortOrder = SortOrderEnum.Desc;

    const response = await makeApiCall(
      () => controller.getPrograms(
        page,
        pageSize,
        sortBy,
        sortOrder,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
