/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.JUST_GAINS_API_LIB_ENVIRONMENT;
  const timeout = process.env.JUST_GAINS_API_LIB_TIMEOUT;
  const accessToken = process.env.JUST_GAINS_API_LIB_ACCESS_TOKEN;
  const xUserRole = process.env.JUST_GAINS_API_LIB_X_USER_ROLE;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (accessToken !== undefined) {
    config.bearerAuthCredentials = { accessToken: accessToken };
  }

  if (xUserRole !== undefined) {
    config.userRolesCredentials = { 'X-User-Role': xUserRole };
  }

  return config;
}
