/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { UsersSocialMediaAccountsController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('UsersSocialMediaAccountsController', () => {
  let controller : UsersSocialMediaAccountsController;

  beforeAll(() => {
    controller = new UsersSocialMediaAccountsController(testClient);
  });

  it('should Test List Users|Social Media Accounts', async () => {
    const response = await makeApiCall(
      () => controller.listUsersSocialMediaAccounts(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
