/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { UsersRoleManagementController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('UsersRoleManagementController', () => {
  let controller : UsersRoleManagementController;

  beforeAll(() => {
    controller = new UsersRoleManagementController(testClient);
  });

  it('should Test Get all roles', async () => {
    const response = await makeApiCall(
      () => controller.getAllRoles()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
