/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { UserManagementController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('UserManagementController', () => {
  let controller : UserManagementController;

  beforeAll(() => {
    controller = new UserManagementController(testClient);
  });

  it('should Test Get current user information', async () => {
    const response = await makeApiCall(
      () => controller.getCurrentUserInformation()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
