/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { UsersController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('UsersController', () => {
  let controller : UsersController;

  beforeAll(() => {
    controller = new UsersController(testClient);
  });

  it('should Test Get a list of all users for admin management', async () => {
    const response = await makeApiCall(
      () => controller.getAListOfAllUsersForAdminManagement()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test Get a user by ID', async () => {
    const userId = '123e4567-e89b-12d3-a456-426614174000';

    const response = await makeApiCall(
      () => controller.getAUserByID(userId)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
