/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { UsersCreatorProfilesController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('UsersCreatorProfilesController', () => {
  let controller : UsersCreatorProfilesController;

  beforeAll(() => {
    controller = new UsersCreatorProfilesController(testClient);
  });

  it('should Test getCreatorProfiles', async () => {
    const page = 1;

    const limit = 20;

    const response = await makeApiCall(
      () => controller.getCreatorProfiles(page, limit)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
