/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { SortBy1Enum, SortOrderEnum, WorkoutsController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('WorkoutsController', () => {
  let controller : WorkoutsController;

  beforeAll(() => {
    controller = new WorkoutsController(testClient);
  });

  it('should Test Get a paginated list of workouts', async () => {
    const page = 1;

    const pageSize = 20;

    const sortBy = SortBy1Enum.CreatedAt;

    const sortOrder = SortOrderEnum.Desc;

    const response = await makeApiCall(
      () => controller.getAPaginatedListOfWorkouts(
        page,
        pageSize,
        sortBy,
        sortOrder
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
