/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of AuthResetPassword400
 */
interface AuthResetPassword400 {
  status: string;
  message: string;
  errors?: string[];
}

export class AuthResetPassword400Error extends ApiError<AuthResetPassword400> {}
