/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of CreatorProfiles401
 */
interface CreatorProfiles401 {
  status: string;
  message: string;
  errors?: string[];
}

export class CreatorProfiles401Error extends ApiError<CreatorProfiles401> {}
