/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of CreatorProfiles404
 */
interface CreatorProfiles404 {
  status: string;
  message: string;
  errors?: string[];
}

export class CreatorProfiles404Error extends ApiError<CreatorProfiles404> {}
