/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of CreatorProfiles500
 */
interface CreatorProfiles500 {
  status: string;
  message: string;
  errors?: string[];
}

export class CreatorProfiles500Error extends ApiError<CreatorProfiles500> {}
