/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of CreatorProfiles400
 */
interface CreatorProfiles400 {
  status: string;
  message: string;
  errors?: string[];
}

export class CreatorProfiles400Error extends ApiError<CreatorProfiles400> {}
