/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EquipmentTranslations404
 */
interface EquipmentTranslations404 {
  status: string;
  message: string;
  errors?: string[];
}

export class EquipmentTranslations404Error extends ApiError<
  EquipmentTranslations404
> {}
