/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Equipment400
 */
interface Equipment400 {
  status: string;
  message: string;
  errors?: string[];
}

export class Equipment400Error extends ApiError<Equipment400> {}
