/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EquipmentTranslations400
 */
interface EquipmentTranslations400 {
  status: string;
  message: string;
  errors?: string[];
}

export class EquipmentTranslations400Error extends ApiError<
  EquipmentTranslations400
> {}
