/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Equipment409
 */
interface Equipment409 {
  status: string;
  message: string;
  errors?: string[];
}

export class Equipment409Error extends ApiError<Equipment409> {}
