/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Equipment404
 */
interface Equipment404 {
  status: string;
  message: string;
  errors?: string[];
}

export class Equipment404Error extends ApiError<Equipment404> {}
