/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EquipmentTranslations404
 */
interface EquipmentTranslations404 {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  errors?: unknown;
}

export class EquipmentTranslations404Error extends ApiError<
  EquipmentTranslations404
> {}
