/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EquipmentGroups404
 */
interface EquipmentGroups404 {
  status: string;
  message: string;
  errors?: string[];
}

export class EquipmentGroups404Error extends ApiError<EquipmentGroups404> {}
