/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EquipmentGroupsTranslations422
 */
interface EquipmentGroupsTranslations422 {
  status: string;
  message: string;
  errors?: string[];
}

export class EquipmentGroupsTranslations422Error extends ApiError<
  EquipmentGroupsTranslations422
> {}
