/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesInstructionsUserId404
 */
interface ExercisesInstructionsUserId404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesInstructionsUserId404Error extends ApiError<
  ExercisesInstructionsUserId404
> {}
