/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Exercises404
 */
interface Exercises404 {
  status: string;
  message: string;
  errors?: string[];
}

export class Exercises404Error extends ApiError<Exercises404> {}
