/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesInstructions401
 */
interface ExercisesInstructions401 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesInstructions401Error extends ApiError<
  ExercisesInstructions401
> {}
