/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesVideos401
 */
interface ExercisesVideos401 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesVideos401Error extends ApiError<ExercisesVideos401> {}
