/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesInstructionsUserId401
 */
interface ExercisesInstructionsUserId401 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesInstructionsUserId401Error extends ApiError<
  ExercisesInstructionsUserId401
> {}
