/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesVideos404
 */
interface ExercisesVideos404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesVideos404Error extends ApiError<ExercisesVideos404> {}
