/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseCategoriesTranslations404
 */
interface ExerciseCategoriesTranslations404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseCategoriesTranslations404Error extends ApiError<
  ExerciseCategoriesTranslations404
> {}
