/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesMuscleGroups404
 */
interface ExercisesMuscleGroups404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesMuscleGroups404Error extends ApiError<
  ExercisesMuscleGroups404
> {}
