/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesVideosExerciseVideoId401
 */
interface ExercisesVideosExerciseVideoId401 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesVideosExerciseVideoId401Error extends ApiError<
  ExercisesVideosExerciseVideoId401
> {}
