/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesVideos400
 */
interface ExercisesVideos400 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesVideos400Error extends ApiError<ExercisesVideos400> {}
