/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseCategories400
 */
interface ExerciseCategories400 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseCategories400Error extends ApiError<
  ExerciseCategories400
> {}
