/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseCategoriesTranslations400
 */
interface ExerciseCategoriesTranslations400 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseCategoriesTranslations400Error extends ApiError<
  ExerciseCategoriesTranslations400
> {}
