/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Exercises500
 */
interface Exercises500 {
  status: string;
  message: string;
  errors?: string[];
}

export class Exercises500Error extends ApiError<Exercises500> {}
