/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseMetrics404
 */
interface ExerciseMetrics404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseMetrics404Error extends ApiError<ExerciseMetrics404> {}
