/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseCategories404
 */
interface ExerciseCategories404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseCategories404Error extends ApiError<
  ExerciseCategories404
> {}
