/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseDraft400
 */
interface ExerciseDraft400 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseDraft400Error extends ApiError<ExerciseDraft400> {}
