/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExerciseDraft404
 */
interface ExerciseDraft404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExerciseDraft404Error extends ApiError<ExerciseDraft404> {}
