/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesTranslations404
 */
interface ExercisesTranslations404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesTranslations404Error extends ApiError<
  ExercisesTranslations404
> {}
