/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesVideosExerciseVideoId404
 */
interface ExercisesVideosExerciseVideoId404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesVideosExerciseVideoId404Error extends ApiError<
  ExercisesVideosExerciseVideoId404
> {}
