/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ExercisesInstructionsUserId400
 */
interface ExercisesInstructionsUserId400 {
  status: string;
  message: string;
  errors?: string[];
}

export class ExercisesInstructionsUserId400Error extends ApiError<
  ExercisesInstructionsUserId400
> {}
