/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of M400
 */
interface M400 {
  status: string;
  message: string;
}

export class M400Error extends ApiError<M400> {}
