/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of MediaAssets404
 */
interface MediaAssets404 {
  status: string;
  message: string;
  errors?: string[];
}

export class MediaAssets404Error extends ApiError<MediaAssets404> {}
