/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of MusclesTranslations401
 */
interface MusclesTranslations401 {
  status: string;
  message: string;
  errors?: string[];
}

export class MusclesTranslations401Error extends ApiError<
  MusclesTranslations401
> {}
