/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of MuscleGroups400
 */
interface MuscleGroups400 {
  status: string;
  message: string;
  errors?: string[];
}

export class MuscleGroups400Error extends ApiError<MuscleGroups400> {}
