/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Muscles400
 */
interface Muscles400 {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** A list of error messages that occurred during the operation. */
  errors?: string[];
  error?: unknown;
}

export class Muscles400Error extends ApiError<Muscles400> {}
