/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of MuscleGroupsTranslations400
 */
interface MuscleGroupsTranslations400 {
  status: string;
  message: string;
  errors?: string[];
}

export class MuscleGroupsTranslations400Error extends ApiError<
  MuscleGroupsTranslations400
> {}
