/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Muscles400
 */
interface Muscles400 {
  status: string;
  message: string;
}

export class Muscles400Error extends ApiError<Muscles400> {}
