/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ProgramsViews404
 */
interface ProgramsViews404 {
  status: string;
  message: string;
  errors?: string[];
}

export class ProgramsViews404Error extends ApiError<ProgramsViews404> {}
