/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Programs404
 */
interface Programs404 {
  status: string;
  message: string;
  errors?: string[];
}

export class Programs404Error extends ApiError<Programs404> {}
