/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PublishedStatus404
 */
interface PublishedStatus404 {
  status: string;
  message: string;
  errors?: string[];
}

export class PublishedStatus404Error extends ApiError<PublishedStatus404> {}
