/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PublishedStatusTranslations404
 */
interface PublishedStatusTranslations404 {
  status: string;
  message: string;
  errors?: string[];
}

export class PublishedStatusTranslations404Error extends ApiError<
  PublishedStatusTranslations404
> {}
