/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Users403
 */
interface Users403 {
  status: string;
  message: string;
  errors?: string[];
}

export class Users403Error extends ApiError<Users403> {}
