/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Users404
 */
interface Users404 {
  status: string;
  message: string;
  errors?: string[];
}

export class Users404Error extends ApiError<Users404> {}
