/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Users401
 */
interface Users401 {
  status: string;
  message: string;
  errors?: string[];
}

export class Users401Error extends ApiError<Users401> {}
