/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Workouts400
 */
interface Workouts400 {
  status: string;
  message: string;
  errors?: string[];
}

export class Workouts400Error extends ApiError<Workouts400> {}
