/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of WorkoutsDuplicate404
 */
interface WorkoutsDuplicate404 {
  status: string;
  message: string;
  errors?: string[];
}

export class WorkoutsDuplicate404Error extends ApiError<WorkoutsDuplicate404> {}
