/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Workouts404
 */
interface Workouts404 {
  status: string;
  message: string;
  errors?: string[];
}

export class Workouts404Error extends ApiError<Workouts404> {}
