/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Equipment, equipmentSchema } from '../models/equipment';
import {
  EquipmentListResponse,
  equipmentListResponseSchema,
} from '../models/equipmentListResponse';
import {
  EquipmentResponse,
  equipmentResponseSchema,
} from '../models/equipmentResponse';
import {
  EquipmentTranslation,
  equipmentTranslationSchema,
} from '../models/equipmentTranslation';
import {
  EquipmentTranslationListResponse,
  equipmentTranslationListResponseSchema,
} from '../models/equipmentTranslationListResponse';
import {
  JustGainsBasicResponse,
  justGainsBasicResponseSchema,
} from '../models/justGainsBasicResponse';
import { optional, string } from '../schema';
import { BaseController } from './baseController';
import { EquipmentTranslations400Error } from '../errors/equipmentTranslations400Error';
import { EquipmentTranslations404Error } from '../errors/equipmentTranslations404Error';
import { JustGainsErrorResponseError } from '../errors/justGainsErrorResponseError';

export class EquipmentController extends BaseController {
  /**
   * @param localeCode The locale to use for the localized equipment names.
   * @return Response from the API call
   */
  async getEquipments(
    localeCode?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<EquipmentListResponse>> {
    const req = this.createRequest('GET', '/equipment');
    const mapped = req.prepareArgs({
      localeCode: [localeCode, optional(string())],
    });
    req.query('localeCode', mapped.localeCode);
    req.authenticate(false);
    return req.callAsJson(equipmentListResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createEquipment(
    body: Equipment,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('POST', '/equipment');
    const mapped = req.prepareArgs({ body: [body, equipmentSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, JustGainsErrorResponseError, 'Invalid request data.');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }

  /**
   * @param equipmentCode The unique code identifying the equipment.
   * @param localeCode    The locale to use for the localized equipment names.
   * @return Response from the API call
   */
  async getEquipment(
    equipmentCode: string,
    localeCode?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<EquipmentResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      equipmentCode: [equipmentCode, string()],
      localeCode: [localeCode, optional(string())],
    });
    req.query('localeCode', mapped.localeCode);
    req.appendTemplatePath`/equipment/${mapped.equipmentCode}`;
    req.throwOn(
      404,
      JustGainsErrorResponseError,
      'Equipment not found with the given code.'
    );
    req.authenticate(false);
    return req.callAsJson(equipmentResponseSchema, requestOptions);
  }

  /**
   * @param equipmentCode The unique code identifying the equipment to update.
   * @param body
   * @return Response from the API call
   */
  async updateEquipment(
    equipmentCode: string,
    body: Equipment,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      equipmentCode: [equipmentCode, string()],
      body: [body, equipmentSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/equipment/${mapped.equipmentCode}`;
    req.throwOn(
      400,
      JustGainsErrorResponseError,
      'Bad request. Invalid input data.'
    );
    req.throwOn(
      404,
      JustGainsErrorResponseError,
      'Equipment not found with the given code.'
    );
    req.throwOn(
      409,
      JustGainsErrorResponseError,
      'Conflict. The equipment code already exists for a different equipment.'
    );
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }

  /**
   * @param equipmentCode The unique code identifying the equipment to delete.
   * @return Response from the API call
   */
  async deleteEquipment(
    equipmentCode: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      equipmentCode: [equipmentCode, string()],
    });
    req.appendTemplatePath`/equipment/${mapped.equipmentCode}`;
    req.throwOn(
      400,
      JustGainsErrorResponseError,
      'Failed to delete the equipment or equipment does not exist.'
    );
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }

  /**
   * @param equipmentCode The unique code of the equipment
   * @return Response from the API call
   */
  async getEquipmentTranslations(
    equipmentCode: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<EquipmentTranslationListResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      equipmentCode: [equipmentCode, string()],
    });
    req.appendTemplatePath`/equipment/${mapped.equipmentCode}/translations`;
    req.throwOn(400, EquipmentTranslations400Error, 'Bad request');
    req.throwOn(404, EquipmentTranslations404Error, 'Equipment not found');
    req.authenticate(false);
    return req.callAsJson(
      equipmentTranslationListResponseSchema,
      requestOptions
    );
  }

  /**
   * @param equipmentCode The unique code of the equipment
   * @param body
   * @return Response from the API call
   */
  async updateEquipmentTranslations(
    equipmentCode: string,
    body: EquipmentTranslation,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      equipmentCode: [equipmentCode, string()],
      body: [body, equipmentTranslationSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/equipment/${mapped.equipmentCode}/translations`;
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.throwOn(404, JustGainsErrorResponseError, 'Equipment not found');
    req.authenticate(false);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }
}
