/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ExerciseDraftDTO,
  exerciseDraftDTOSchema,
} from '../models/exerciseDraftDTO';
import {
  ExerciseDraftResponse,
  exerciseDraftResponseSchema,
} from '../models/exerciseDraftResponse';
import { BaseController } from './baseController';
import { ExerciseDraft400Error } from '../errors/exerciseDraft400Error';
import { ExerciseDraft404Error } from '../errors/exerciseDraft404Error';

export class ExerciseDraftsController extends BaseController {
  /**
   * Create or Update an existing exercise with the Exercise Draft format
   *
   * @param body
   * @return Response from the API call
   */
  async exerciseDraftFormat(
    body: ExerciseDraftDTO,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ExerciseDraftResponse>> {
    const req = this.createRequest('PUT', '/exercise-draft');
    const mapped = req.prepareArgs({ body: [body, exerciseDraftDTOSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ExerciseDraft400Error, 'Bad request');
    req.throwOn(404, ExerciseDraft404Error, 'Exercise not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(exerciseDraftResponseSchema, requestOptions);
  }
}
