/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  MusclesResponse,
  musclesResponseSchema,
} from '../models/musclesResponse';
import {
  MusclesResponse1,
  musclesResponse1Schema,
} from '../models/musclesResponse1';
import {
  MusclesTranslationsResponse,
  musclesTranslationsResponseSchema,
} from '../models/musclesTranslationsResponse';
import {
  MusclesTranslationsResponse1,
  musclesTranslationsResponse1Schema,
} from '../models/musclesTranslationsResponse1';
import {
  MuscleTranslation,
  muscleTranslationSchema,
} from '../models/muscleTranslation';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';
import { Muscles400Error } from '../errors/muscles400Error';
import { Muscles404Error } from '../errors/muscles404Error';
import { MusclesTranslations400Error } from '../errors/musclesTranslations400Error';
import { MusclesTranslations401Error } from '../errors/musclesTranslations401Error';
import { MusclesTranslations404Error } from '../errors/musclesTranslations404Error';

export class MusclesController extends BaseController {
  /**
   * @param localeCode Locale code to filter muscles by language
   * @return Response from the API call
   */
  async getMuscles(
    localeCode?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MusclesResponse>> {
    const req = this.createRequest('GET', '/muscles');
    const mapped = req.prepareArgs({
      localeCode: [localeCode, optional(string())],
    });
    req.query('localeCode', mapped.localeCode);
    req.throwOn(400, Muscles400Error, 'Failed to retrieve muscles');
    req.authenticate(false);
    return req.callAsJson(musclesResponseSchema, requestOptions);
  }

  /**
   * @param muscleCode The muscle code to retrieve.
   * @param localeCode Example: en-US
   * @return Response from the API call
   */
  async getMuscle(
    muscleCode: string,
    localeCode?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MusclesResponse1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      muscleCode: [muscleCode, string()],
      localeCode: [localeCode, optional(string())],
    });
    req.query('localeCode', mapped.localeCode);
    req.appendTemplatePath`/muscles/${mapped.muscleCode}`;
    req.throwOn(400, Muscles400Error, 'Failed to retrieve muscle');
    req.throwOn(404, Muscles404Error, 'Muscle not found');
    req.authenticate(false);
    return req.callAsJson(musclesResponse1Schema, requestOptions);
  }

  /**
   * @param muscleCode The unique identifier code of the muscle to retrieve translations for
   * @return Response from the API call
   */
  async getMuscleTranslations(
    muscleCode: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MusclesTranslationsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ muscleCode: [muscleCode, string()] });
    req.appendTemplatePath`/muscles/${mapped.muscleCode}/translations`;
    req.throwOn(
      400,
      MusclesTranslations400Error,
      'Failed to retrieve muscle translations'
    );
    req.throwOn(404, MusclesTranslations404Error, 'Muscle not found');
    req.authenticate(false);
    return req.callAsJson(musclesTranslationsResponseSchema, requestOptions);
  }

  /**
   * @param muscleCode   The unique identifier code of the muscle to update translations for
   * @param body
   * @return Response from the API call
   */
  async updateMuscleTranslations(
    muscleCode: string,
    body: MuscleTranslation[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MusclesTranslationsResponse1>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      muscleCode: [muscleCode, string()],
      body: [body, array(muscleTranslationSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/muscles/${mapped.muscleCode}/translations`;
    req.throwOn(
      400,
      MusclesTranslations400Error,
      'Failed to update muscle translations'
    );
    req.throwOn(401, MusclesTranslations401Error, 'Unauthorized');
    req.throwOn(404, MusclesTranslations404Error, 'Muscle not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(musclesTranslationsResponse1Schema, requestOptions);
  }
}
