/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ProgramReview, programReviewSchema } from '../models/programReview';
import {
  ProgramsReviewsResponse,
  programsReviewsResponseSchema,
} from '../models/programsReviewsResponse';
import {
  ProgramsReviewsResponse1,
  programsReviewsResponse1Schema,
} from '../models/programsReviewsResponse1';
import { number } from '../schema';
import { BaseController } from './baseController';
import { ProgramsReviews400Error } from '../errors/programsReviews400Error';
import { ProgramsReviews404Error } from '../errors/programsReviews404Error';

export class ProgramsProgramReviewsController extends BaseController {
  /**
   * @param programId
   * @return Response from the API call
   */
  async getReviewsProgram(
    programId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProgramsReviewsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ programId: [programId, number()] });
    req.appendTemplatePath`/programs/${mapped.programId}/reviews`;
    req.throwOn(404, ProgramsReviews404Error, 'Program not found');
    req.authenticate(false);
    return req.callAsJson(programsReviewsResponseSchema, requestOptions);
  }

  /**
   * @param programId
   * @param body
   * @return Response from the API call
   */
  async addReviewProgram(
    programId: number,
    body: ProgramReview,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProgramsReviewsResponse1>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      programId: [programId, number()],
      body: [body, programReviewSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/programs/${mapped.programId}/reviews`;
    req.throwOn(400, ProgramsReviews400Error, 'Bad request');
    req.throwOn(404, ProgramsReviews404Error, 'Program not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(programsReviewsResponse1Schema, requestOptions);
  }
}
