/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ProgramReview, programReviewSchema } from '../models/programReview';
import {
  ProgramReviewResponse,
  programReviewResponseSchema,
} from '../models/programReviewResponse';
import { number } from '../schema';
import { BaseController } from './baseController';
import { JustGainsErrorResponseError } from '../errors/justGainsErrorResponseError';

export class ProgramsProgramReviewsController extends BaseController {
  /**
   * @param programId
   * @return Response from the API call
   */
  async getReviewsProgram(
    programId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProgramReviewResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ programId: [programId, number()] });
    req.appendTemplatePath`/programs/${mapped.programId}/reviews`;
    req.throwOn(404, JustGainsErrorResponseError, 'Program not found');
    req.authenticate(false);
    return req.callAsJson(programReviewResponseSchema, requestOptions);
  }

  /**
   * @param programId
   * @param body
   * @return Response from the API call
   */
  async addReviewProgram(
    programId: number,
    body: ProgramReview,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProgramReviewResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      programId: [programId, number()],
      body: [body, programReviewSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/programs/${mapped.programId}/reviews`;
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.throwOn(404, JustGainsErrorResponseError, 'Program not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(programReviewResponseSchema, requestOptions);
  }
}
