/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { BaseController } from './baseController';
import { ApiError } from '@apimatic/core';
import { JustGainsResponseError } from '../errors/justGainsResponseError';

export class StatusController extends BaseController {
  /**
   * Returns a simple message to indicate that the API is working.
   *
   * @return Response from the API call
   */
  async checkServerAlive(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET', '/');
    req.throwOn(400, ApiError, 'Bad request');
    req.throwOn(404, ApiError, 'Not found');
    req.authenticate(false);
    return req.callAsText(requestOptions);
  }

  /**
   * Returns a JSON response simulating an unauthorized access attempt.
   *
   * @return Response from the API call
   */
  async testUnauthorized(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/test/unauthorized');
    req.throwOn(401, JustGainsResponseError, 'Unauthorized response');
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
