/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { CreatorProfile, creatorProfileSchema } from '../models/creatorProfile';
import {
  CreatorProfileListResponse,
  creatorProfileListResponseSchema,
} from '../models/creatorProfileListResponse';
import {
  CreatorProfileResponse,
  creatorProfileResponseSchema,
} from '../models/creatorProfileResponse';
import {
  JustGainsBasicResponse,
  justGainsBasicResponseSchema,
} from '../models/justGainsBasicResponse';
import { number, optional, string } from '../schema';
import { BaseController } from './baseController';
import { JustGainsErrorResponseError } from '../errors/justGainsErrorResponseError';

export class UsersCreatorProfilesController extends BaseController {
  /**
   * @param limit Number of items per page
   * @param page  Page number for pagination
   * @return Response from the API call
   */
  async getCreatorProfiles(
    limit?: number,
    page?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreatorProfileListResponse>> {
    const req = this.createRequest('GET', '/creator-profiles');
    const mapped = req.prepareArgs({
      limit: [limit, optional(number())],
      page: [page, optional(number())],
    });
    req.query('limit', mapped.limit);
    req.query('page', mapped.page);
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.authenticate(false);
    return req.callAsJson(creatorProfileListResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createCreatorProfile(
    body: CreatorProfile,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreatorProfileResponse>> {
    const req = this.createRequest('POST', '/creator-profiles');
    const mapped = req.prepareArgs({ body: [body, creatorProfileSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.throwOn(401, JustGainsErrorResponseError, 'Unauthorized');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(creatorProfileResponseSchema, requestOptions);
  }

  /**
   * @param creatorProfileId
   * @return Response from the API call
   */
  async getCreatorProfile(
    creatorProfileId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreatorProfileResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      creatorProfileId: [creatorProfileId, string()],
    });
    req.appendTemplatePath`/creator-profiles/${mapped.creatorProfileId}`;
    req.throwOn(404, JustGainsErrorResponseError, 'Creator profile not found');
    req.authenticate(false);
    return req.callAsJson(creatorProfileResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @param creatorProfileId
   * @return Response from the API call
   */
  async updateCreatorProfile(
    body: CreatorProfile,
    creatorProfileId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreatorProfileResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      body: [body, creatorProfileSchema],
      creatorProfileId: [creatorProfileId, string()],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/creator-profiles/${mapped.creatorProfileId}`;
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.throwOn(401, JustGainsErrorResponseError, 'Unauthorized');
    req.throwOn(404, JustGainsErrorResponseError, 'Creator profile not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(creatorProfileResponseSchema, requestOptions);
  }

  /**
   * @param creatorProfileId
   * @return Response from the API call
   */
  async deleteCreatorProfile(
    creatorProfileId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      creatorProfileId: [creatorProfileId, string()],
    });
    req.appendTemplatePath`/creator-profiles/${mapped.creatorProfileId}`;
    req.throwOn(401, JustGainsErrorResponseError, 'Unauthorized');
    req.throwOn(404, JustGainsErrorResponseError, 'Creator profile not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }
}
