/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  JustGainsBasicResponse,
  justGainsBasicResponseSchema,
} from '../models/justGainsBasicResponse';
import {
  JustGainsResponse,
  justGainsResponseSchema,
} from '../models/justGainsResponse';
import { SortOrderEnum, sortOrderEnumSchema } from '../models/sortOrderEnum';
import { WorkoutRequest, workoutRequestSchema } from '../models/workoutRequest';
import {
  WorkoutResponse,
  workoutResponseSchema,
} from '../models/workoutResponse';
import {
  WorkoutsDuplicateRequest,
  workoutsDuplicateRequestSchema,
} from '../models/workoutsDuplicateRequest';
import {
  WorkoutTableListResponse,
  workoutTableListResponseSchema,
} from '../models/workoutTableListResponse';
import { WorkoutUpdate, workoutUpdateSchema } from '../models/workoutUpdate';
import { number, optional, string } from '../schema';
import { BaseController } from './baseController';
import { ApiError } from '@apimatic/core';
import { JustGainsErrorResponseError } from '../errors/justGainsErrorResponseError';

export class WorkoutsController extends BaseController {
  /**
   * @param page      The page number to retrieve
   * @param pageSize  The number of items to retrieve per page
   * @param sortBy
   * @param sortOrder The order to sort the results in
   * @return Response from the API call
   */
  async getAPaginatedListOfWorkouts(
    page?: number,
    pageSize?: number,
    sortBy?: string,
    sortOrder?: SortOrderEnum,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutTableListResponse>> {
    const req = this.createRequest('GET', '/workouts');
    const mapped = req.prepareArgs({
      page: [page, optional(number())],
      pageSize: [pageSize, optional(number())],
      sortBy: [sortBy, optional(string())],
      sortOrder: [sortOrder, optional(sortOrderEnumSchema)],
    });
    req.query('page', mapped.page);
    req.query('pageSize', mapped.pageSize);
    req.query('sortBy', mapped.sortBy);
    req.query('sortOrder', mapped.sortOrder);
    req.throwOn(
      400,
      JustGainsErrorResponseError,
      'Invalid pagination parameters'
    );
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutTableListResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createANewWorkout(
    body: WorkoutRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutResponse>> {
    const req = this.createRequest('POST', '/workouts');
    const mapped = req.prepareArgs({ body: [body, workoutRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, JustGainsErrorResponseError, 'Invalid workout data');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutResponseSchema, requestOptions);
  }

  /**
   * @param workoutId The ID of the workout to retrieve
   * @return Response from the API call
   */
  async getAWorkoutByID(
    workoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ workoutId: [workoutId, string()] });
    req.appendTemplatePath`/workouts/${mapped.workoutId}`;
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutResponseSchema, requestOptions);
  }

  /**
   * @param workoutId    The ID of the workout to update
   * @param body
   * @return Response from the API call
   */
  async updateAWorkoutByID(
    workoutId: string,
    body: WorkoutUpdate,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      workoutId: [workoutId, string()],
      body: [body, workoutUpdateSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/workouts/${mapped.workoutId}`;
    req.throwOn(400, JustGainsErrorResponseError, 'Invalid workout data');
    req.throwOn(403, JustGainsErrorResponseError, 'Permission denied');
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutResponseSchema, requestOptions);
  }

  /**
   * Soft-deletes a workout and all associated data
   *
   * @param workoutId The ID of the workout to delete
   * @return Response from the API call
   */
  async deleteAWorkout(
    workoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ workoutId: [workoutId, string()] });
    req.appendTemplatePath`/workouts/${mapped.workoutId}`;
    req.throwOn(400, JustGainsErrorResponseError, 'Invalid workout ID format');
    req.throwOn(403, JustGainsErrorResponseError, 'Permission denied');
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(justGainsResponseSchema, requestOptions);
  }

  /**
   * @param workoutSlug The URL slug of the workout
   * @return Response from the API call
   */
  async getAWorkoutByWorkoutSlug(
    workoutSlug: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ workoutSlug: [workoutSlug, string()] });
    req.appendTemplatePath`/workouts/${mapped.workoutSlug}`;
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutResponseSchema, requestOptions);
  }

  /**
   * Adds the specified workout to the current user's bookmarks. If the workout is already bookmarked,
   * the request is idempotent and will not create a duplicate.
   *
   * @param workoutId The unique identifier of the workout to bookmark
   * @return Response from the API call
   */
  async bookmarkWorkout(
    workoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({ workoutId: [workoutId, string()] });
    req.appendTemplatePath`/workouts/${mapped.workoutId}/bookmark`;
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.throwOn(401, ApiError, '');
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([]);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }

  /**
   * Removes the specified workout from the current user's bookmarks. If the workout is not bookmarked,
   * the request is idempotent and will not result in an error.
   *
   * @param workoutId The unique identifier of the workout to remove from bookmarks
   * @return Response from the API call
   */
  async removeWorkoutBookmark(
    workoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JustGainsBasicResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ workoutId: [workoutId, string()] });
    req.appendTemplatePath`/workouts/${mapped.workoutId}/bookmark`;
    req.throwOn(400, JustGainsErrorResponseError, 'Bad request');
    req.throwOn(401, ApiError, '');
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([]);
    return req.callAsJson(justGainsBasicResponseSchema, requestOptions);
  }

  /**
   * Creates a copy of an existing workout, preserving creator credits and adding the current user as a
   * new contributor.
   *
   * @param workoutId    The ID of the workout to duplicate
   * @param body
   * @return Response from the API call
   */
  async duplicateAWorkout(
    workoutId: string,
    body: WorkoutsDuplicateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      workoutId: [workoutId, string()],
      body: [body, workoutsDuplicateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/workouts/${mapped.workoutId}/duplicate`;
    req.throwOn(400, JustGainsErrorResponseError, 'Invalid request data');
    req.throwOn(403, JustGainsErrorResponseError, 'Permission denied');
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutResponseSchema, requestOptions);
  }
}
