/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { SortBy1Enum, sortBy1EnumSchema } from '../models/sortBy1Enum';
import { SortOrderEnum, sortOrderEnumSchema } from '../models/sortOrderEnum';
import { Workout, workoutSchema } from '../models/workout';
import {
  WorkoutsDuplicateRequest,
  workoutsDuplicateRequestSchema,
} from '../models/workoutsDuplicateRequest';
import {
  WorkoutsDuplicateResponse,
  workoutsDuplicateResponseSchema,
} from '../models/workoutsDuplicateResponse';
import {
  WorkoutsResponse,
  workoutsResponseSchema,
} from '../models/workoutsResponse';
import {
  WorkoutsResponse1,
  workoutsResponse1Schema,
} from '../models/workoutsResponse1';
import { number, optional } from '../schema';
import { BaseController } from './baseController';
import { Workouts400Error } from '../errors/workouts400Error';
import { Workouts404Error } from '../errors/workouts404Error';
import { WorkoutsDuplicate400Error } from '../errors/workoutsDuplicate400Error';
import { WorkoutsDuplicate403Error } from '../errors/workoutsDuplicate403Error';
import { WorkoutsDuplicate404Error } from '../errors/workoutsDuplicate404Error';

export class WorkoutsController extends BaseController {
  /**
   * @param page      The page number to retrieve
   * @param pageSize  The number of items to retrieve per page
   * @param sortBy    The field to sort the results by
   * @param sortOrder The order to sort the results in
   * @return Response from the API call
   */
  async getAPaginatedListOfWorkouts(
    page?: number,
    pageSize?: number,
    sortBy?: SortBy1Enum,
    sortOrder?: SortOrderEnum,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutsResponse>> {
    const req = this.createRequest('GET', '/workouts');
    const mapped = req.prepareArgs({
      page: [page, optional(number())],
      pageSize: [pageSize, optional(number())],
      sortBy: [sortBy, optional(sortBy1EnumSchema)],
      sortOrder: [sortOrder, optional(sortOrderEnumSchema)],
    });
    req.query('page', mapped.page);
    req.query('pageSize', mapped.pageSize);
    req.query('sortBy', mapped.sortBy);
    req.query('sortOrder', mapped.sortOrder);
    req.throwOn(400, Workouts400Error, 'Invalid pagination parameters');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutsResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createANewWorkout(
    body: Workout,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutsResponse1>> {
    const req = this.createRequest('POST', '/workouts');
    const mapped = req.prepareArgs({ body: [body, workoutSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, Workouts400Error, 'Invalid workout data');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutsResponse1Schema, requestOptions);
  }

  /**
   * @param workoutId
   * @return Response from the API call
   */
  async getAWorkoutByID(
    workoutId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutsResponse1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ workoutId: [workoutId, number()] });
    req.appendTemplatePath`/workouts/${mapped.workoutId}`;
    req.throwOn(404, Workouts404Error, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutsResponse1Schema, requestOptions);
  }

  /**
   * Creates a copy of an existing workout, preserving creator credits and adding the current user as a
   * new contributor.
   *
   * @param workoutId    The ID of the workout to duplicate
   * @param body
   * @return Response from the API call
   */
  async duplicateAWorkout(
    workoutId: number,
    body: WorkoutsDuplicateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutsDuplicateResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      workoutId: [workoutId, number()],
      body: [body, workoutsDuplicateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/workouts/${mapped.workoutId}/duplicate`;
    req.throwOn(400, WorkoutsDuplicate400Error, 'Invalid request data');
    req.throwOn(403, WorkoutsDuplicate403Error, 'Permission denied');
    req.throwOn(404, WorkoutsDuplicate404Error, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutsDuplicateResponseSchema, requestOptions);
  }
}
