/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  WorkoutPreviewResponse,
  workoutPreviewResponseSchema,
} from '../models/workoutPreviewResponse';
import { string } from '../schema';
import { BaseController } from './baseController';
import { JustGainsErrorResponseError } from '../errors/justGainsErrorResponseError';

export class WorkoutsWorkoutPreviewController extends BaseController {
  /**
   * @param workoutId The ID of the workout to retrieve
   * @return Response from the API call
   */
  async getWorkoutPreviewByID(
    workoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WorkoutPreviewResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ workoutId: [workoutId, string()] });
    req.appendTemplatePath`/workouts/${mapped.workoutId}/preview`;
    req.throwOn(404, JustGainsErrorResponseError, 'Workout not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(workoutPreviewResponseSchema, requestOptions);
  }
}
