/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  OAuthSettingsData,
  oAuthSettingsDataSchema,
} from './oAuthSettingsData';

export interface AuthSettingsResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Data object containing OAuth provider settings */
  data: OAuthSettingsData;
}

export const authSettingsResponseSchema: Schema<AuthSettingsResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => oAuthSettingsDataSchema)],
});
