/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data13, data13Schema } from './data13';

export interface AuthSigninResponse {
  status: string;
  message: string;
  data?: Data13;
}

export const authSigninResponseSchema: Schema<AuthSigninResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => data13Schema))],
});
