/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, unknown } from '../schema';
import { OAuthStateData, oAuthStateDataSchema } from './oAuthStateData';

export interface AuthInitiateResponse {
  /** Data object containing OAuth state information */
  data?: OAuthStateData;
  message?: unknown;
  status?: unknown;
}

export const authInitiateResponseSchema: Schema<AuthInitiateResponse> = object({
  data: ['data', optional(lazy(() => oAuthStateDataSchema))],
  message: ['message', optional(unknown())],
  status: ['status', optional(unknown())],
});
