/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface AuthForgotPasswordResponse {
  status: string;
  message: string;
}

export const authForgotPasswordResponseSchema: Schema<AuthForgotPasswordResponse> = object(
  { status: ['status', string()], message: ['message', string()] }
);
