/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { UserInfo1, userInfo1Schema } from './userInfo1';

/** Response object for authentication operations */
export interface AuthResponse {
  /** JWT access token for authenticated requests */
  accessToken?: string;
  /** JWT refresh token for obtaining new access tokens */
  refreshToken?: string;
  /** Expiration time of the access token */
  tokenExpiration?: string;
  /** User information */
  userInfo?: UserInfo1;
}

export const authResponseSchema: Schema<AuthResponse> = object({
  accessToken: ['accessToken', optional(string())],
  refreshToken: ['refreshToken', optional(string())],
  tokenExpiration: ['tokenExpiration', optional(string())],
  userInfo: ['userInfo', optional(lazy(() => userInfo1Schema))],
});
