/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { User, userSchema } from './user';

/** Authentication data containing tokens and user information */
export interface AuthData {
  /** JWT access token for authenticated requests */
  accessToken?: string;
  /** JWT refresh token for obtaining new access tokens */
  refreshToken?: string;
  /** Expiration time of the access token */
  tokenExpiration?: string;
  /** Represents a user in the system. */
  userInfo?: User;
}

export const authDataSchema: Schema<AuthData> = object({
  accessToken: ['accessToken', optional(string())],
  refreshToken: ['refreshToken', optional(string())],
  tokenExpiration: ['tokenExpiration', optional(string())],
  userInfo: ['userInfo', optional(lazy(() => userSchema))],
});
