/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { AuthData, authDataSchema } from './authData';

export interface AuthSigninResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Authentication data containing tokens and user information */
  data: AuthData;
}

export const authSigninResponseSchema: Schema<AuthSigninResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => authDataSchema)],
});
