/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ContributionTypeEnum
 */
export enum ContributionTypeEnum {
  ORIGINALAUTHOR = 'ORIGINAL_AUTHOR',
  PARTIALCONTRIBUTOR = 'PARTIAL_CONTRIBUTOR',
  SUBMITTER = 'SUBMITTER',
  CURATOR = 'CURATOR',
}

/**
 * Schema for ContributionTypeEnum
 */
export const contributionTypeEnumSchema: Schema<ContributionTypeEnum> = stringEnum(
  ContributionTypeEnum
);
