/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data9, data9Schema } from './data9';

export interface CreatorProfilesResponse1 {
  status: string;
  message: string;
  data?: Data9;
}

export const creatorProfilesResponse1Schema: Schema<CreatorProfilesResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => data9Schema))],
  }
);
