/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { CreatorProfile, creatorProfileSchema } from './creatorProfile';
import { Pagination, paginationSchema } from './pagination';

export interface CreatorProfilesResponse {
  status: string;
  message: string;
  data?: CreatorProfile[];
  pagination?: Pagination;
}

export const creatorProfilesResponseSchema: Schema<CreatorProfilesResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => creatorProfileSchema)))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
  }
);
