/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Data2 {
  /** The authorization URL to redirect the user to */
  uri?: string;
  /** The PKCE verifier code for the OAuth flow */
  pkceVerifier?: string;
}

export const data2Schema: Schema<Data2> = object({
  uri: ['uri', optional(string())],
  pkceVerifier: ['pkceVerifier', optional(string())],
});
