/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Data17 {
  /** Unique identifier for the media element. */
  mediaId?: string;
  /** The name of the file, which may be useful for generating URLs or simple validations. */
  fileName?: string;
  /** The relative path to the file within the storage system, useful for constructing URLs. */
  filePath?: string;
  /** The URL to the media file, which may be useful for embedding or downloading. */
  fileUrl?: string;
  /** File size in bytes */
  fileSize?: number;
  /** File format, extension */
  fileFormat?: string;
  /** Description of the media element */
  description?: string;
}

export const data17Schema: Schema<Data17> = object({
  mediaId: ['mediaId', optional(string())],
  fileName: ['fileName', optional(string())],
  filePath: ['filePath', optional(string())],
  fileUrl: ['fileUrl', optional(string())],
  fileSize: ['fileSize', optional(number())],
  fileFormat: ['fileFormat', optional(string())],
  description: ['description', optional(string())],
});
