/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface Data {
  text?: string | null;
}

export const dataSchema: Schema<Data> = object({
  text: ['text', optional(nullable(string()))],
});
