/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Data38 {
  /** Unique identifier for the exercise category. */
  exerciseCategoryCode?: string;
  /** The name of the exercise category in the default language (typically English). This is a read-only field derived from translations. */
  exerciseCategoryName?: string;
}

export const data38Schema: Schema<Data38> = object({
  exerciseCategoryCode: ['exerciseCategoryCode', optional(string())],
  exerciseCategoryName: ['exerciseCategoryName', optional(string())],
});
