/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, nullable, object, optional, Schema, string } from '../schema';

export interface Data43 {
  /** A unique identifier for the equipment. */
  equipmentCode?: string;
  /** The name of the equipment, localized. */
  equipmentName?: string;
  /** An optional thumbnail image representing the equipment. */
  equipmentThumbnail?: string | null;
  /** A list of equipment groups this equipment belongs to. */
  equipmentEquipmentGroups?: string[] | null;
}

export const data43Schema: Schema<Data43> = object({
  equipmentCode: ['equipmentCode', optional(string())],
  equipmentName: ['equipmentName', optional(string())],
  equipmentThumbnail: ['equipmentThumbnail', optional(nullable(string()))],
  equipmentEquipmentGroups: [
    'equipmentEquipmentGroups',
    optional(nullable(array(string()))),
  ],
});
