/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { UserInfo, userInfoSchema } from './userInfo';

export interface Data3 {
  /** The access token received from the OAuth provider */
  accessToken?: string;
  /** The refresh token received from the OAuth provider */
  refreshToken?: string;
  /** User information object */
  user?: UserInfo;
}

export const data3Schema: Schema<Data3> = object({
  accessToken: ['accessToken', optional(string())],
  refreshToken: ['refreshToken', optional(string())],
  user: ['user', optional(lazy(() => userInfoSchema))],
});
