/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { ProgramThumbnail, programThumbnailSchema } from './programThumbnail';

export interface Data67 {
  /** Unique identifier for the program. */
  programId?: number;
  /** Identifier of the user who created the program. */
  userId?: string;
  /** Name of the training program. */
  programName?: string;
  /** Detailed description of the program, its goals, and target audience. */
  programDescription?: string;
  /** Thumbnail image representing the program. */
  programThumbnail?: ProgramThumbnail;
  /** Code indicating the publish status of the program (e.g., draft, published, archived). */
  publishStatusCode?: string;
  /** Timestamp of when the program was created. */
  createdAt?: string;
  /** Timestamp of when the program was last updated. */
  updatedAt?: string;
  /** Timestamp of when the program was soft deleted, if applicable. */
  deletedAt?: string;
  /** Identifier of the user who deleted the program, if applicable. */
  deletedBy?: string;
}

export const data67Schema: Schema<Data67> = object({
  programId: ['programId', optional(number())],
  userId: ['userId', optional(string())],
  programName: ['programName', optional(string())],
  programDescription: ['programDescription', optional(string())],
  programThumbnail: [
    'programThumbnail',
    optional(lazy(() => programThumbnailSchema)),
  ],
  publishStatusCode: ['publishStatusCode', optional(string())],
  createdAt: ['createdAt', optional(string())],
  updatedAt: ['updatedAt', optional(string())],
  deletedAt: ['deletedAt', optional(string())],
  deletedBy: ['deletedBy', optional(string())],
});
