/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Data72 {
  /** Unique identifier for this analytics entry. */
  analyticsId?: number;
  /** Identifier of the program these analytics belong to. */
  programId?: number;
  /** Number of times the program has been started by users. */
  startCount?: number;
  /** Number of times the program has been completed by users. */
  completionCount?: number;
  /** Average rating of the program (typically out of 5). */
  averageRating?: number;
  /** Timestamp of when these analytics were last updated. */
  lastUpdated?: string;
}

export const data72Schema: Schema<Data72> = object({
  analyticsId: ['analyticsId', optional(number())],
  programId: ['programId', optional(number())],
  startCount: ['startCount', optional(number())],
  completionCount: ['completionCount', optional(number())],
  averageRating: ['averageRating', optional(number())],
  lastUpdated: ['lastUpdated', optional(string())],
});
