/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  MuscleTranslation,
  muscleTranslationSchema,
} from './muscleTranslation';

export interface Data25 {
  /** Unique identifier for the muscle */
  muscleCode?: string;
  /** The name of the muscle in the default language (typically English) */
  muscleName?: string;
  /** Array of translations for the muscle name in different languages. This is a write-only field used when creating or updating muscles. */
  muscleTranslations?: MuscleTranslation[];
}

export const data25Schema: Schema<Data25> = object({
  muscleCode: ['muscleCode', optional(string())],
  muscleName: ['muscleName', optional(string())],
  muscleTranslations: [
    'muscleTranslations',
    optional(array(lazy(() => muscleTranslationSchema))),
  ],
});
