/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface Data4 {
  text?: string | null;
}

export const data4Schema: Schema<Data4> = object({
  text: ['text', optional(nullable(string()))],
});
