/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface EquipmentRequired {
  required?: string[];
  optional?: string[];
}

export const equipmentRequiredSchema: Schema<EquipmentRequired> = object({
  required: ['required', optional(array(string()))],
  optional: ['optional', optional(array(string()))],
});
