/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Equipment, equipmentSchema } from './equipment';

export interface EquipmentResponse {
  status: string;
  message: string;
  data?: Equipment[];
}

export const equipmentResponseSchema: Schema<EquipmentResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(array(lazy(() => equipmentSchema)))],
});
