/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data46, data46Schema } from './data46';

export interface EquipmentTranslationsResponse {
  status: string;
  message: string;
  data?: Data46;
}

export const equipmentTranslationsResponseSchema: Schema<EquipmentTranslationsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => data46Schema))],
  }
);
