/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { EquipmentGroup, equipmentGroupSchema } from './equipmentGroup';

export interface EquipmentGroupsResponse1 {
  status: string;
  message: string;
  data?: EquipmentGroup;
}

export const equipmentGroupsResponse1Schema: Schema<EquipmentGroupsResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => equipmentGroupSchema))],
  }
);
