/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface EquipmentTranslation {
  localeCode?: string | null;
  equipmentName: string;
}

export const equipmentTranslationSchema: Schema<EquipmentTranslation> = object({
  localeCode: ['localeCode', optional(nullable(string()))],
  equipmentName: ['equipmentName', string()],
});
