/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  EquipmentGroupList,
  equipmentGroupListSchema,
} from './equipmentGroupList';

export interface EquipmentGroupsResponse {
  status: string;
  message: string;
  data?: EquipmentGroupList[];
}

export const equipmentGroupsResponseSchema: Schema<EquipmentGroupsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => equipmentGroupListSchema)))],
  }
);
