/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EquipmentGroupTypeEnum
 */
export enum EquipmentGroupTypeEnum {
  MainGroup = 'main_group',
  Subgroup = 'subgroup',
  ExerciseGroup = 'exercise_group',
}

/**
 * Schema for EquipmentGroupTypeEnum
 */
export const equipmentGroupTypeEnumSchema: Schema<EquipmentGroupTypeEnum> = stringEnum(
  EquipmentGroupTypeEnum
);
