/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Link to the thumbnail image for the equipment group. */
export interface EquipmentThumbnail1 {
  /** Unique identifier for the media element. */
  mediaId: string;
  /** The name of the file, which may be useful for generating URLs or simple validations. */
  fileName: string;
  /** The relative path to the file within the storage system, useful for constructing URLs. */
  filePath: string;
  /** The URL to the media file, which may be useful for embedding or downloading. */
  fileUrl?: string;
  /** File size in bytes */
  fileSize: number;
  /** File format, extension */
  fileFormat: string;
  /** Description of the media element */
  description?: string;
}

export const equipmentThumbnail1Schema: Schema<EquipmentThumbnail1> = object({
  mediaId: ['mediaId', string()],
  fileName: ['fileName', string()],
  filePath: ['filePath', string()],
  fileUrl: ['fileUrl', optional(string())],
  fileSize: ['fileSize', number()],
  fileFormat: ['fileFormat', string()],
  description: ['description', optional(string())],
});
