/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  EquipmentGroupTypeEnum,
  equipmentGroupTypeEnumSchema,
} from './equipmentGroupTypeEnum';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';
import { Subgroup, subgroupSchema } from './subgroup';

export interface EquipmentGroupList {
  /** Unique identifier for the equipment group. */
  equipmentGroupCode?: string;
  /** The localized name of the equipment group */
  equipmentGroupName?: string;
  equipmentGroupType?: EquipmentGroupTypeEnum;
  /** parent group CODE for hierarchical structuring. */
  equipmentGroupParent?: string | null;
  subgroups?: Subgroup[];
  equipmentGroupEquipment?: string[];
  equipmentThumbnail?: MediaAsset;
  /** Used to sort the equipment groups */
  sortOrder?: number;
}

export const equipmentGroupListSchema: Schema<EquipmentGroupList> = object({
  equipmentGroupCode: ['equipmentGroupCode', optional(string())],
  equipmentGroupName: ['equipmentGroupName', optional(string())],
  equipmentGroupType: [
    'equipmentGroupType',
    optional(equipmentGroupTypeEnumSchema),
  ],
  equipmentGroupParent: ['equipmentGroupParent', optional(nullable(string()))],
  subgroups: ['subgroups', optional(array(lazy(() => subgroupSchema)))],
  equipmentGroupEquipment: [
    'equipmentGroupEquipment',
    optional(array(string())),
  ],
  equipmentThumbnail: [
    'equipmentThumbnail',
    optional(lazy(() => mediaAssetSchema)),
  ],
  sortOrder: ['sortOrder', optional(number())],
});
