/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface EquipmentGroupTranslation {
  /** The locale code for this translation */
  localeCode: string;
  /** The translated name of the equipment group */
  equipmentGroupName: string;
  /** The translated description of the equipment group */
  equipmentGroupDescription?: string;
}

export const equipmentGroupTranslationSchema: Schema<EquipmentGroupTranslation> = object(
  {
    localeCode: ['localeCode', string()],
    equipmentGroupName: ['equipmentGroupName', string()],
    equipmentGroupDescription: [
      'equipmentGroupDescription',
      optional(string()),
    ],
  }
);
