/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Equipment, equipmentSchema } from './equipment';

export interface EquipmentResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Represents a piece of exercise equipment with its details and translations. */
  data: Equipment;
}

export const equipmentResponseSchema: Schema<EquipmentResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => equipmentSchema)],
});
