/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';

export interface ExerciseVideo {
  /** Unique identifier for the exercise. */
  exerciseCode?: string;
  /** The user ID of the user who created the exercise. */
  userId?: string;
  /** Username of the user who created the video. */
  userName?: string;
  mediaAsset?: MediaAsset;
  /** The order in which the video should be displayed. */
  sortOrder?: number;
}

export const exerciseVideoSchema: Schema<ExerciseVideo> = object({
  exerciseCode: ['exerciseCode', optional(string())],
  userId: ['userId', optional(string())],
  userName: ['userName', optional(string())],
  mediaAsset: ['mediaAsset', optional(lazy(() => mediaAssetSchema))],
  sortOrder: ['sortOrder', optional(number())],
});
