/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ExerciseList, exerciseListSchema } from './exerciseList';

export interface ExercisesResponse1 {
  status: string;
  message: string;
  data?: ExerciseList;
}

export const exercisesResponse1Schema: Schema<ExercisesResponse1> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => exerciseListSchema))],
});
