/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ExerciseDraftDTO, exerciseDraftDTOSchema } from './exerciseDraftDTO';

export interface ExerciseDraftResponse {
  status: string;
  message: string;
  data?: ExerciseDraftDTO;
}

export const exerciseDraftResponseSchema: Schema<ExerciseDraftResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => exerciseDraftDTOSchema))],
  }
);
