/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { InstructionJSON, instructionJSONSchema } from './instructionJSON';

/** The data returned by the operation. */
export interface ExerciseInstruction1 {
  /** The exerciseCode of the exercise to add instructions to. */
  exerciseCode: string;
  /** The userId of the creator related to this instruction */
  userId?: string;
  /** Language code for the instructions */
  localeCode: string;
  instructionJSON: InstructionJSON;
}

export const exerciseInstruction1Schema: Schema<ExerciseInstruction1> = object({
  exerciseCode: ['exerciseCode', string()],
  userId: ['userId', optional(string())],
  localeCode: ['localeCode', string()],
  instructionJSON: ['instructionJSON', lazy(() => instructionJSONSchema)],
});
