/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ExerciseMetric1 {
  /** The code of the metric being recorded. */
  metricCode?: string;
  /** The unit of measurement for this metric. */
  metricUnit?: string;
}

export const exerciseMetric1Schema: Schema<ExerciseMetric1> = object({
  metricCode: ['metricCode', optional(string())],
  metricUnit: ['metricUnit', optional(string())],
});
