/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  ExerciseInstruction,
  exerciseInstructionSchema,
} from './exerciseInstruction';

export interface ExerciseInstructionResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  data: ExerciseInstruction;
}

export const exerciseInstructionResponseSchema: Schema<ExerciseInstructionResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => exerciseInstructionSchema)],
  }
);
