/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ExerciseVideoListItem {
  userId?: string;
  dateUpdated?: string;
  dateCreated?: string;
}

export const exerciseVideoListItemSchema: Schema<ExerciseVideoListItem> = object(
  {
    userId: ['userId', optional(string())],
    dateUpdated: ['dateUpdated', optional(string())],
    dateCreated: ['dateCreated', optional(string())],
  }
);
