/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ExerciseVideo, exerciseVideoSchema } from './exerciseVideo';

export interface ExercisesVideosResponse2 {
  status: string;
  message: string;
  data?: ExerciseVideo[];
}

export const exercisesVideosResponse2Schema: Schema<ExercisesVideosResponse2> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => exerciseVideoSchema)))],
  }
);
