/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ExerciseTranslation,
  exerciseTranslationSchema,
} from './exerciseTranslation';

export interface ExercisesTranslationsResponse {
  status: string;
  message: string;
  data?: ExerciseTranslation[];
}

export const exercisesTranslationsResponseSchema: Schema<ExercisesTranslationsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => exerciseTranslationSchema)))],
  }
);
