/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data82, data82Schema } from './data82';

export interface ExercisesInstructionsResponse1 {
  status: string;
  message: string;
  data?: Data82;
}

export const exercisesInstructionsResponse1Schema: Schema<ExercisesInstructionsResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => data82Schema))],
  }
);
