/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ExerciseMetric, exerciseMetricSchema } from './exerciseMetric';

export interface ExerciseMetricsResponse {
  status: string;
  message: string;
  data?: ExerciseMetric[];
}

export const exerciseMetricsResponseSchema: Schema<ExerciseMetricsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => exerciseMetricSchema)))],
  }
);
