/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ExerciseList, exerciseListSchema } from './exerciseList';
import { Pagination, paginationSchema } from './pagination';

export interface ExercisesResponse {
  status: string;
  message: string;
  data?: ExerciseList[];
  pagination?: Pagination;
}

export const exercisesResponseSchema: Schema<ExercisesResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(array(lazy(() => exerciseListSchema)))],
  pagination: ['pagination', optional(lazy(() => paginationSchema))],
});
