/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ExerciseInstructionListItem {
  userId?: string;
  /** Language code for the instructions */
  localeCode?: string;
  dateUpdated?: string;
  dateCreated?: string;
}

export const exerciseInstructionListItemSchema: Schema<ExerciseInstructionListItem> = object(
  {
    userId: ['userId', optional(string())],
    localeCode: ['localeCode', optional(string())],
    dateUpdated: ['dateUpdated', optional(string())],
    dateCreated: ['dateCreated', optional(string())],
  }
);
