/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExerciseGroupTypeEnum
 */
export enum ExerciseGroupTypeEnum {
  SUPERSET = 'SUPERSET',
  INTERVAL = 'INTERVAL',
  WARMUP = 'WARMUP',
  COOLDOWN = 'COOLDOWN',
  SECTION = 'SECTION',
}

/**
 * Schema for ExerciseGroupTypeEnum
 */
export const exerciseGroupTypeEnumSchema: Schema<ExerciseGroupTypeEnum> = stringEnum(
  ExerciseGroupTypeEnum
);
