/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface ExerciseMetricTranslation {
  /** The locale code of the translation */
  localeCode: string;
  /** Translated Metric Name for the chosen Locale */
  exerciseMetricName: string;
  /** JSONB format containing measurement details */
  measurementData?: unknown;
}

export const exerciseMetricTranslationSchema: Schema<ExerciseMetricTranslation> = object(
  {
    localeCode: ['localeCode', string()],
    exerciseMetricName: ['exerciseMetricName', string()],
    measurementData: ['measurementData', optional(unknown())],
  }
);
