/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface ExerciseTranslation {
  /** The locale code of the translation */
  localeCode?: string;
  /** Translated Primary Exercise Name for the chosen Locale */
  exerciseName?: string;
  /** Is this the primary translation for the exercise in the chosen locale */
  isPrimary?: boolean;
}

export const exerciseTranslationSchema: Schema<ExerciseTranslation> = object({
  localeCode: ['localeCode', optional(string())],
  exerciseName: ['exerciseName', optional(string())],
  isPrimary: ['isPrimary', optional(boolean())],
});
