/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ExerciseEquipment {
  /** Array of equipment code arrays that are required for this exercise */
  required?: string[];
  /** Array of equipment code arrays that are optional for this exercise */
  optional?: string[];
}

export const exerciseEquipmentSchema: Schema<ExerciseEquipment> = object({
  required: ['required', optional(array(string()))],
  optional: ['optional', optional(array(string()))],
});
