/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ExerciseCategoryTranslation,
  exerciseCategoryTranslationSchema,
} from './exerciseCategoryTranslation';

export interface ExerciseCategoriesTranslationsResponse {
  status: string;
  message: string;
  data?: ExerciseCategoryTranslation[];
}

export const exerciseCategoriesTranslationsResponseSchema: Schema<ExerciseCategoriesTranslationsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: [
      'data',
      optional(array(lazy(() => exerciseCategoryTranslationSchema))),
    ],
  }
);
