/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ExerciseMetricTranslation,
  exerciseMetricTranslationSchema,
} from './exerciseMetricTranslation';
import { MeasurementData, measurementDataSchema } from './measurementData';

/** Represents a metric associated with an exercise, including how it should be displayed. */
export interface ExerciseMetric {
  /** A unique identifier for the exercise metric. */
  exerciseMetricCode?: string;
  /** Translated name of the metric (Realistically not used because the real data for this comes from measurementData) */
  exerciseMetricName?: string;
  exerciseMetricTranslations?: ExerciseMetricTranslation[];
  measurementData?: MeasurementData;
}

export const exerciseMetricSchema: Schema<ExerciseMetric> = object({
  exerciseMetricCode: ['exerciseMetricCode', optional(string())],
  exerciseMetricName: ['exerciseMetricName', optional(string())],
  exerciseMetricTranslations: [
    'exerciseMetricTranslations',
    optional(array(lazy(() => exerciseMetricTranslationSchema))),
  ],
  measurementData: [
    'measurementData',
    optional(lazy(() => measurementDataSchema)),
  ],
});
