/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ExerciseMetricTranslation {
  /** The locale code for this translation */
  localeCode?: string;
  /** Translated name of the metric */
  metricName?: string;
  /** a custom JSON object that can be used to store any additional data related to the metric */
  measurementData?: string;
}

export const exerciseMetricTranslationSchema: Schema<ExerciseMetricTranslation> = object(
  {
    localeCode: ['localeCode', optional(string())],
    metricName: ['metricName', optional(string())],
    measurementData: ['measurementData', optional(string())],
  }
);
