/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Exercise, exerciseSchema } from './exercise';

export interface ExercisesResponse2 {
  status: string;
  message: string;
  data?: Exercise;
}

export const exercisesResponse2Schema: Schema<ExercisesResponse2> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => exerciseSchema))],
});
