/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Represents a category for exercises, including its code and translations. */
export interface ExerciseCategory {
  /** Unique identifier for the exercise category. */
  exerciseCategoryCode?: string;
  /** The name of the exercise category in the default language (typically English). This is a read-only field derived from translations. */
  exerciseCategoryName?: string;
}

export const exerciseCategorySchema: Schema<ExerciseCategory> = object({
  exerciseCategoryCode: ['exerciseCategoryCode', optional(string())],
  exerciseCategoryName: ['exerciseCategoryName', optional(string())],
});
