/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ExerciseVideo, exerciseVideoSchema } from './exerciseVideo';

export interface ExercisesVideosResponse1 {
  status: string;
  message: string;
  data?: ExerciseVideo;
}

export const exercisesVideosResponse1Schema: Schema<ExercisesVideosResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => exerciseVideoSchema))],
  }
);
