/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ExerciseMuscle, exerciseMuscleSchema } from './exerciseMuscle';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';

export interface ExerciseListItem {
  /** Unique identifier for the exercise. */
  exerciseCode?: string;
  /** Translated Primary Exercise Name for the chosen Locale */
  exerciseName?: string;
  /** The exerciseTypeCode of the exercise */
  exerciseTypeCode?: string;
  /** Array of category codes associated with this exercise */
  exerciseCategories?: string[];
  /** The publish status of the exercise */
  publishedStatus?: string;
  exerciseMuscles?: ExerciseMuscle[];
  exerciseThumbnail?: MediaAsset;
  /** Array of metric codes associated with this exercise */
  exerciseMetrics?: string[];
  /** Used for sorting by most recently used exercises. */
  recentOrder?: number;
}

export const exerciseListItemSchema: Schema<ExerciseListItem> = object({
  exerciseCode: ['exerciseCode', optional(string())],
  exerciseName: ['exerciseName', optional(string())],
  exerciseTypeCode: ['exerciseTypeCode', optional(string())],
  exerciseCategories: ['exerciseCategories', optional(array(string()))],
  publishedStatus: ['publishedStatus', optional(string())],
  exerciseMuscles: [
    'exerciseMuscles',
    optional(array(lazy(() => exerciseMuscleSchema))),
  ],
  exerciseThumbnail: [
    'exerciseThumbnail',
    optional(lazy(() => mediaAssetSchema)),
  ],
  exerciseMetrics: ['exerciseMetrics', optional(array(string()))],
  recentOrder: ['recentOrder', optional(number())],
});
