/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface ExerciseMuscle {
  /** muscleCode that belongs to this exercise */
  muscleCode?: string;
  /** The percentage of effort targeted at this muscle in the exercise. */
  targetPercentage?: number;
  /** Indicates whether this muscle is the primary muscle used in the exercise. */
  isPrimary?: boolean;
}

export const exerciseMuscleSchema: Schema<ExerciseMuscle> = object({
  muscleCode: ['muscleCode', optional(string())],
  targetPercentage: ['targetPercentage', optional(number())],
  isPrimary: ['isPrimary', optional(boolean())],
});
