/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { InstructionJSON1, instructionJSON1Schema } from './instructionJSON1';

export interface ExerciseInstruction {
  /** The exerciseCode of the exercise to add instructions to. */
  exerciseCode: string;
  /** The userId of the creator related to this instruction */
  userId?: string;
  /** Language code for the instructions */
  localeCode: string;
  /** JSON object containing the exercise instructions in EditorJS format */
  instructionJSON: InstructionJSON1;
}

export const exerciseInstructionSchema: Schema<ExerciseInstruction> = object({
  exerciseCode: ['exerciseCode', string()],
  userId: ['userId', optional(string())],
  localeCode: ['localeCode', string()],
  instructionJSON: ['instructionJSON', lazy(() => instructionJSON1Schema)],
});
