/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';

export interface ExerciseThumbnail {
  /** Unique identifier for the exercise. */
  exerciseCode: string;
  /** The user ID of the user who created the thumbnail. */
  userId: string;
  /** Username of the user who created this Exercise Theme. */
  userName?: string;
  mediaAsset: MediaAsset;
}

export const exerciseThumbnailSchema: Schema<ExerciseThumbnail> = object({
  exerciseCode: ['exerciseCode', string()],
  userId: ['userId', string()],
  userName: ['userName', optional(string())],
  mediaAsset: ['mediaAsset', lazy(() => mediaAssetSchema)],
});
