/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Request object for initiating password reset */
export interface ForgotPasswordRequest {
  /** Email address associated with the account */
  email: string;
}

export const forgotPasswordRequestSchema: Schema<ForgotPasswordRequest> = object(
  { email: ['email', string()] }
);
