/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Request object for initiating OAuth authentication */
export interface InitiateAuthRequest {
  /** The URL to redirect to after authentication */
  redirectUrl: string;
}

export const initiateAuthRequestSchema: Schema<InitiateAuthRequest> = object({
  redirectUrl: ['redirectUrl', string()],
});
