/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data4, data4Schema } from './data4';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface InstructionBlock {
  id?: string;
  type?: TypeEnum;
  data?: Data4;
}

export const instructionBlockSchema: Schema<InstructionBlock> = object({
  id: ['id', optional(string())],
  type: ['type', optional(typeEnumSchema)],
  data: ['data', optional(lazy(() => data4Schema))],
});
