/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string, unknown } from '../schema';
import { Pagination, paginationSchema } from './pagination';

export interface JustGainsPaginationResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data?: unknown;
  pagination?: Pagination;
}

export const justGainsPaginationResponseSchema: Schema<JustGainsPaginationResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(unknown())],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
  }
);
