/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface JustGainsResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data?: unknown;
}

export const justGainsResponseSchema: Schema<JustGainsResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(unknown())],
});
