/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

/** The default Message:Status response model. */
export interface JustGainsDefaultResponse {
  status: string;
  message: string;
  /** Error Responses */
  errors?: string[] | null;
  data?: unknown | null;
}

export const justGainsDefaultResponseSchema: Schema<JustGainsDefaultResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    errors: ['errors', optional(nullable(array(string())))],
    data: ['Data', optional(nullable(unknown()))],
  }
);
