/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Locale, localeSchema } from './locale';

export interface LocalesResponse {
  status: string;
  message: string;
  data?: Locale;
}

export const localesResponseSchema: Schema<LocalesResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => localeSchema))],
});
