/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MediaAssetAssignment {
  /** Unique identifier for the media element. */
  mediaId?: string;
}

export const mediaAssetAssignmentSchema: Schema<MediaAssetAssignment> = object({
  mediaId: ['mediaId', optional(string())],
});
