/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';
import { Pagination, paginationSchema } from './pagination';

export interface MediaAssetListResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: MediaAsset[];
  pagination?: Pagination;
}

export const mediaAssetListResponseSchema: Schema<MediaAssetListResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', array(lazy(() => mediaAssetSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
  }
);
