/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { MediaAsset1, mediaAsset1Schema } from './mediaAsset1';

export interface MediaAssetResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: MediaAsset1;
}

export const mediaAssetResponseSchema: Schema<MediaAssetResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => mediaAsset1Schema)],
});
