/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data17, data17Schema } from './data17';

export interface MediaAssetsResponse1 {
  status: string;
  message: string;
  data?: Data17;
}

export const mediaAssetsResponse1Schema: Schema<MediaAssetsResponse1> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => data17Schema))],
});
