/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MuscleGroupDto {
  /** The unique code of the muscle group */
  muscleGroupCode?: string;
  /** The localized name of the muscle group */
  muscleGroupName?: string;
}

export const muscleGroupDtoSchema: Schema<MuscleGroupDto> = object({
  muscleGroupCode: ['muscleGroupCode', optional(string())],
  muscleGroupName: ['muscleGroupName', optional(string())],
});
