/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  MuscleTranslation,
  muscleTranslationSchema,
} from './muscleTranslation';

export interface MusclesTranslationsResponse {
  status: string;
  message: string;
  data?: MuscleTranslation[];
}

export const musclesTranslationsResponseSchema: Schema<MusclesTranslationsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => muscleTranslationSchema)))],
  }
);
