/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { MuscleGroupDto, muscleGroupDtoSchema } from './muscleGroupDto';

export interface MuscleGroupDtoResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  data: MuscleGroupDto;
}

export const muscleGroupDtoResponseSchema: Schema<MuscleGroupDtoResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => muscleGroupDtoSchema)],
  }
);
