/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { MuscleGroup, muscleGroupSchema } from './muscleGroup';

export interface MuscleGroupsResponse1 {
  status: string;
  message: string;
  data?: MuscleGroup;
}

export const muscleGroupsResponse1Schema: Schema<MuscleGroupsResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => muscleGroupSchema))],
  }
);
