/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MuscleGroupType4Enum
 */
export enum MuscleGroupType4Enum {
  MainGroup = 'main_group',
  SubGroup = 'sub_group',
}

/**
 * Schema for MuscleGroupType4Enum
 */
export const muscleGroupType4EnumSchema: Schema<MuscleGroupType4Enum> = stringEnum(
  MuscleGroupType4Enum
);
