/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data25, data25Schema } from './data25';

export interface MusclesResponse1 {
  status: string;
  message: string;
  data?: Data25;
}

export const musclesResponse1Schema: Schema<MusclesResponse1> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => data25Schema))],
});
