/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { MuscleGroupList, muscleGroupListSchema } from './muscleGroupList';

export interface MuscleGroupsResponse {
  status: string;
  message: string;
  data?: MuscleGroupList[];
}

export const muscleGroupsResponseSchema: Schema<MuscleGroupsResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(array(lazy(() => muscleGroupListSchema)))],
});
