/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Muscle, muscleSchema } from './muscle';

export interface MusclesResponse {
  status: string;
  message: string;
  data?: Muscle[];
}

export const musclesResponseSchema: Schema<MusclesResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(array(lazy(() => muscleSchema)))],
});
