/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MuscleGroupTranslation {
  /** The locale code for this translation (e.g., 'en-US', 'es-ES') */
  localeCode: string;
  /** The translated name of the muscle group */
  muscleGroupName: string;
  /** The translated description of the muscle group (optional) */
  muscleGroupDescription?: string;
}

export const muscleGroupTranslationSchema: Schema<MuscleGroupTranslation> = object(
  {
    localeCode: ['localeCode', string()],
    muscleGroupName: ['muscleGroupName', string()],
    muscleGroupDescription: ['muscleGroupDescription', optional(string())],
  }
);
