/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';
import {
  MuscleGroupTypeEnum,
  muscleGroupTypeEnumSchema,
} from './muscleGroupTypeEnum';
import { Subgroup1, subgroup1Schema } from './subgroup1';

export interface MuscleGroupList {
  /** The unique code of the muscle group */
  muscleGroupCode?: string;
  /** The localized name of the muscle group */
  muscleGroupName?: string;
  muscleGroupType?: MuscleGroupTypeEnum;
  /** The code of the muscle group that is the parent of this group */
  muscleGroupParent?: string | null;
  subgroups?: Subgroup1[];
  /**
   * An array of muscle codes associated with this muscle group.
   * Each muscle code represents a specific muscle or muscle group targeted in exercises.
   * The codes are used to identify muscles across different languages and provide
   * consistency in muscle targeting for various exercises.
   */
  muscleGroupMuscles?: string[];
  muscleGroupThumbnail?: MediaAsset;
}

export const muscleGroupListSchema: Schema<MuscleGroupList> = object({
  muscleGroupCode: ['muscleGroupCode', optional(string())],
  muscleGroupName: ['muscleGroupName', optional(string())],
  muscleGroupType: ['muscleGroupType', optional(muscleGroupTypeEnumSchema)],
  muscleGroupParent: ['muscleGroupParent', optional(nullable(string()))],
  subgroups: ['subgroups', optional(array(lazy(() => subgroup1Schema)))],
  muscleGroupMuscles: ['muscleGroupMuscles', optional(array(string()))],
  muscleGroupThumbnail: [
    'muscleGroupThumbnail',
    optional(lazy(() => mediaAssetSchema)),
  ],
});
