/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MuscleTranslation {
  /** The muscle code of the translation */
  muscleCode: string;
  /** The locale code of the translation */
  localeCode: string;
  /** The translated name of the muscle */
  muscleName?: string;
}

export const muscleTranslationSchema: Schema<MuscleTranslation> = object({
  muscleCode: ['muscleCode', string()],
  localeCode: ['localeCode', string()],
  muscleName: ['muscleName', optional(string())],
});
