/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MuscleGroupTypeEnum
 */
export enum MuscleGroupTypeEnum {
  MainGroup = 'main_group',
  Subgroup = 'subgroup',
  ExerciseGroup = 'exercise_group',
}

/**
 * Schema for MuscleGroupTypeEnum
 */
export const muscleGroupTypeEnumSchema: Schema<MuscleGroupTypeEnum> = stringEnum(
  MuscleGroupTypeEnum
);
