/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** Data object containing OAuth provider settings */
export interface OAuthSettingsData {
  /** The OAuth client ID */
  clientId: string;
  /** The authorization endpoint URL */
  authorizeUrl: string;
  /** The token endpoint URL */
  tokenUrl: string;
  /** Available OAuth scopes */
  scopes: string[];
}

export const oAuthSettingsDataSchema: Schema<OAuthSettingsData> = object({
  clientId: ['clientId', string()],
  authorizeUrl: ['authorizeUrl', string()],
  tokenUrl: ['tokenUrl', string()],
  scopes: ['scopes', array(string())],
});
