/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Data object containing OAuth state information */
export interface OAuthStateData {
  /** The authorization URL to redirect the user to */
  uri: string;
  /** The PKCE verifier code for the OAuth flow */
  pkceVerifier: string;
}

export const oAuthStateDataSchema: Schema<OAuthStateData> = object({
  uri: ['uri', string()],
  pkceVerifier: ['pkceVerifier', string()],
});
