/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { OAuthStateData, oAuthStateDataSchema } from './oAuthStateData';

/** Response object for OAuth state */
export interface OAuthStateResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Data object containing OAuth state information */
  data: OAuthStateData;
}

export const oAuthStateResponseSchema: Schema<OAuthStateResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => oAuthStateDataSchema)],
});
