/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface Pagination {
  /** The current page number */
  currentPage?: number;
  /** The total number of pages */
  totalPages?: number;
  /** The number of items per page */
  pageSize?: number;
  /** The total number of items across all pages */
  totalCount?: number;
  /** Indicates if there is a previous page */
  hasPrevious?: boolean;
  /** Indicates if there is a next page */
  hasNext?: boolean;
}

export const paginationSchema: Schema<Pagination> = object({
  currentPage: ['currentPage', optional(number())],
  totalPages: ['totalPages', optional(number())],
  pageSize: ['pageSize', optional(number())],
  totalCount: ['totalCount', optional(number())],
  hasPrevious: ['hasPrevious', optional(boolean())],
  hasNext: ['hasNext', optional(boolean())],
});
