/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface ProgramsWeeksResponse {
  message?: unknown;
}

export const programsWeeksResponseSchema: Schema<ProgramsWeeksResponse> = object(
  { message: ['message', optional(unknown())] }
);
