/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';

/** The data returned by the operation. */
export interface Program1 {
  /** Unique identifier for the program. */
  programId: number;
  /** Identifier of the user who created the program. */
  userId: string;
  /** Name of the training program. */
  programName: string;
  /** Detailed description of the program, its goals, and target audience. */
  programDescription: string;
  programThumbnail?: MediaAsset;
  /** Code indicating the publish status of the program (e.g., draft, published, archived). */
  publishStatusCode: string;
  /** Timestamp of when the program was created. */
  createdAt: string;
  /** Timestamp of when the program was last updated. */
  updatedAt: string;
  /** Timestamp of when the program was soft deleted, if applicable. */
  deletedAt?: string;
  /** Identifier of the user who deleted the program, if applicable. */
  deletedBy?: string;
}

export const program1Schema: Schema<Program1> = object({
  programId: ['programId', number()],
  userId: ['userId', string()],
  programName: ['programName', string()],
  programDescription: ['programDescription', string()],
  programThumbnail: [
    'programThumbnail',
    optional(lazy(() => mediaAssetSchema)),
  ],
  publishStatusCode: ['publishStatusCode', string()],
  createdAt: ['createdAt', string()],
  updatedAt: ['updatedAt', string()],
  deletedAt: ['deletedAt', optional(string())],
  deletedBy: ['deletedBy', optional(string())],
});
