/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data71, data71Schema } from './data71';

export interface ProgramsWeeksResponse1 {
  status: string;
  message: string;
  data?: Data71;
}

export const programsWeeksResponse1Schema: Schema<ProgramsWeeksResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => data71Schema))],
  }
);
