/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Pagination, paginationSchema } from './pagination';
import { Program, programSchema } from './program';

export interface ProgramListResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  data: Program[];
  pagination?: Pagination;
}

export const programListResponseSchema: Schema<ProgramListResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', array(lazy(() => programSchema))],
  pagination: ['pagination', optional(lazy(() => paginationSchema))],
});
