/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Week, weekSchema } from './week';

export interface ProgramsWeeksResponse {
  status: string;
  message: string;
  data?: Week[];
}

export const programsWeeksResponseSchema: Schema<ProgramsWeeksResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => weekSchema)))],
  }
);
