/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { ProgramAnalytics, programAnalyticsSchema } from './programAnalytics';

export interface ProgramAnalyticsResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Contains analytics data for a specific program. */
  data: ProgramAnalytics;
}

export const programAnalyticsResponseSchema: Schema<ProgramAnalyticsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => programAnalyticsSchema)],
  }
);
