/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Represents a user's review of a program. */
export interface ProgramReview {
  /** Unique identifier for this review. */
  reviewId: number;
  /** Identifier of the reviewed program. */
  programId: number;
  /** Identifier of the user who wrote the review. */
  userId: string;
  /** Numeric rating given by the user (1 to 5). */
  rating: number;
  /** Text content of the review. */
  reviewText?: string;
  /** Timestamp of when the review was created. */
  createdAt: string;
}

export const programReviewSchema: Schema<ProgramReview> = object({
  reviewId: ['reviewId', number()],
  programId: ['programId', number()],
  userId: ['userId', string()],
  rating: ['rating', number()],
  reviewText: ['reviewText', optional(string())],
  createdAt: ['createdAt', string()],
});
