/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Program1, program1Schema } from './program1';

export interface ProgramResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: Program1;
}

export const programResponseSchema: Schema<ProgramResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => program1Schema)],
});
