/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  ProgramAnalytics1,
  programAnalytics1Schema,
} from './programAnalytics1';

export interface ProgramAnalyticsResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: ProgramAnalytics1;
}

export const programAnalyticsResponseSchema: Schema<ProgramAnalyticsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => programAnalytics1Schema)],
  }
);
