/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Program, programSchema } from './program';

export interface ProgramResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Represents a training program consisting of multiple weeks and workouts. */
  data: Program;
}

export const programResponseSchema: Schema<ProgramResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => programSchema)],
});
