/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ProgramReview, programReviewSchema } from './programReview';

export interface ProgramsReviewsResponse {
  status: string;
  message: string;
  data?: ProgramReview[];
}

export const programsReviewsResponseSchema: Schema<ProgramsReviewsResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => programReviewSchema)))],
  }
);
