/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PublishedStatus {
  /** The unique code for the published status */
  publishedStatusCode?: string;
  /** Comma-separated list of user roles that have access */
  userRoleAccess?: string;
  /** The name of the published status */
  publishedStatusName?: string;
}

export const publishedStatusSchema: Schema<PublishedStatus> = object({
  publishedStatusCode: ['publishedStatusCode', optional(string())],
  userRoleAccess: ['userRoleAccess', optional(string())],
  publishedStatusName: ['publishedStatusName', optional(string())],
});
