/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PublishedStatusTranslationsResponse1 {
  status: string;
  message: string;
}

export const publishedStatusTranslationsResponse1Schema: Schema<PublishedStatusTranslationsResponse1> = object(
  { status: ['status', string()], message: ['message', string()] }
);
