/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { PublishedStatus, publishedStatusSchema } from './publishedStatus';

export interface PublishedStatusResponse {
  status: string;
  message: string;
  data?: PublishedStatus[];
}

export const publishedStatusResponseSchema: Schema<PublishedStatusResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(array(lazy(() => publishedStatusSchema)))],
  }
);
