/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { PublishedStatus, publishedStatusSchema } from './publishedStatus';

export interface PublishedStatusResponse1 {
  status: string;
  message: string;
  data?: PublishedStatus;
}

export const publishedStatusResponse1Schema: Schema<PublishedStatusResponse1> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', optional(lazy(() => publishedStatusSchema))],
  }
);
