/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Role {
  roleId?: number;
  roleName?: string;
  description?: string;
}

export const roleSchema: Schema<Role> = object({
  roleId: ['roleId', optional(number())],
  roleName: ['roleName', optional(string())],
  description: ['description', optional(string())],
});
