/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface RoleUpdateRequest {
  roleName?: string;
  description?: string;
}

export const roleUpdateRequestSchema: Schema<RoleUpdateRequest> = object({
  roleName: ['roleName', optional(string())],
  description: ['description', optional(string())],
});
