/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Role, roleSchema } from './role';

export interface RolesResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  data: Role[];
}

export const rolesResponseSchema: Schema<RolesResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', array(lazy(() => roleSchema))],
});
