/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  SocialMediaPlatform,
  socialMediaPlatformSchema,
} from './socialMediaPlatform';

export interface SocialMediaPlatformResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  data: SocialMediaPlatform;
}

export const socialMediaPlatformResponseSchema: Schema<SocialMediaPlatformResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => socialMediaPlatformSchema)],
  }
);
