/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SocialMediaPlatform {
  /** Unique identifier for the social media platform */
  socialMediaPlatformCode?: string;
  /** Name of the social media platform */
  socialMediaPlatformName?: string;
  /** URL format for the platform's profile pages */
  socialMediaPlatformUrlFormat?: string;
  /** UUID of the associated MediaAsset for the platform's icon */
  socialMediaPlatformIcon?: string;
}

export const socialMediaPlatformSchema: Schema<SocialMediaPlatform> = object({
  socialMediaPlatformCode: ['socialMediaPlatformCode', optional(string())],
  socialMediaPlatformName: ['socialMediaPlatformName', optional(string())],
  socialMediaPlatformUrlFormat: [
    'socialMediaPlatformUrlFormat',
    optional(string()),
  ],
  socialMediaPlatformIcon: ['socialMediaPlatformIcon', optional(string())],
});
