/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SortBy1Enum
 */
export enum SortBy1Enum {
  CreatedAt = 'createdAt',
  UpdatedAt = 'updatedAt',
  Title = 'title',
}

/**
 * Schema for SortBy1Enum
 */
export const sortBy1EnumSchema: Schema<SortBy1Enum> = stringEnum(SortBy1Enum);
