/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  MuscleGroupTypeEnum,
  muscleGroupTypeEnumSchema,
} from './muscleGroupTypeEnum';
import { Subgroup4, subgroup4Schema } from './subgroup4';

export interface Subgroup3 {
  /** The unique code of the muscle subgroup */
  muscleGroupCode?: string;
  /** The localized name of the muscle subgroup */
  muscleGroupName?: string;
  muscleGroupType?: MuscleGroupTypeEnum;
  /** The code of the parent muscle group */
  muscleGroupParent?: string;
  subgroups?: Subgroup4[];
}

export const subgroup3Schema: Schema<Subgroup3> = object({
  muscleGroupCode: ['muscleGroupCode', optional(string())],
  muscleGroupName: ['muscleGroupName', optional(string())],
  muscleGroupType: ['muscleGroupType', optional(muscleGroupTypeEnumSchema)],
  muscleGroupParent: ['muscleGroupParent', optional(string())],
  subgroups: ['subgroups', optional(array(lazy(() => subgroup4Schema)))],
});
