/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';
import {
  EquipmentGroupTypeEnum,
  equipmentGroupTypeEnumSchema,
} from './equipmentGroupTypeEnum';

export interface Subgroup {
  /** Unique identifier for the equipment group. */
  equipmentGroupCode?: string;
  /** The localized name of the equipment group */
  equipmentGroupName?: string;
  equipmentGroupType?: EquipmentGroupTypeEnum;
  /** parent group CODE for hierarchical structuring. */
  equipmentGroupParent?: string | null;
}

export const subgroupSchema: Schema<Subgroup> = object({
  equipmentGroupCode: ['equipmentGroupCode', optional(string())],
  equipmentGroupName: ['equipmentGroupName', optional(string())],
  equipmentGroupType: [
    'equipmentGroupType',
    optional(equipmentGroupTypeEnumSchema),
  ],
  equipmentGroupParent: ['equipmentGroupParent', optional(nullable(string()))],
});
