/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  MuscleGroupType4Enum,
  muscleGroupType4EnumSchema,
} from './muscleGroupType4Enum';

export interface Subgroup4 {
  /** The unique code of the muscle subgroup */
  muscleGroupCode?: string;
  /** The localized name of the muscle subgroup */
  muscleGroupName?: string;
  muscleGroupType?: MuscleGroupType4Enum;
}

export const subgroup4Schema: Schema<Subgroup4> = object({
  muscleGroupCode: ['muscleGroupCode', optional(string())],
  muscleGroupName: ['muscleGroupName', optional(string())],
  muscleGroupType: ['muscleGroupType', optional(muscleGroupType4EnumSchema)],
});
