/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  MuscleGroupTypeEnum,
  muscleGroupTypeEnumSchema,
} from './muscleGroupTypeEnum';
import { Subgroup2, subgroup2Schema } from './subgroup2';

export interface Subgroup1 {
  /** The unique code of the muscle subgroup */
  muscleGroupCode?: string;
  /** The localized name of the muscle subgroup */
  muscleGroupName?: string;
  muscleGroupType?: MuscleGroupTypeEnum;
  /** The code of the parent muscle group */
  muscleGroupParent?: string;
  subgroups?: Subgroup2[];
}

export const subgroup1Schema: Schema<Subgroup1> = object({
  muscleGroupCode: ['muscleGroupCode', optional(string())],
  muscleGroupName: ['muscleGroupName', optional(string())],
  muscleGroupType: ['muscleGroupType', optional(muscleGroupTypeEnumSchema)],
  muscleGroupParent: ['muscleGroupParent', optional(string())],
  subgroups: ['subgroups', optional(array(lazy(() => subgroup2Schema)))],
});
