/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TargetMuscleDTO {
  id?: number;
  muscleName?: string;
  targetPercentage?: number;
}

export const targetMuscleDTOSchema: Schema<TargetMuscleDTO> = object({
  id: ['id', optional(number())],
  muscleName: ['muscle_name', optional(string())],
  targetPercentage: ['target_percentage', optional(number())],
});
