/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UnitLong {
  unitLongName?: string;
  unitLongPlural?: string;
}

export const unitLongSchema: Schema<UnitLong> = object({
  unitLongName: ['unitLongName', optional(string())],
  unitLongPlural: ['unitLongPlural', optional(string())],
});
