/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ImperialUnits, imperialUnitsSchema } from './imperialUnits';
import { MetricUnits, metricUnitsSchema } from './metricUnits';

export interface Units {
  metricUnits?: MetricUnits;
  imperialUnits?: ImperialUnits;
}

export const unitsSchema: Schema<Units> = object({
  metricUnits: ['metricUnits', optional(lazy(() => metricUnitsSchema))],
  imperialUnits: ['imperialUnits', optional(lazy(() => imperialUnitsSchema))],
});
