/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UnitShort {
  unitShortName?: string;
  unitShortPlural?: string;
}

export const unitShortSchema: Schema<UnitShort> = object({
  unitShortName: ['unitShortName', optional(string())],
  unitShortPlural: ['unitShortPlural', optional(string())],
});
