/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { User, userSchema } from './user';

/** Request object for updating user information */
export interface UpdateUserRequest {
  /** Represents a user in the system. */
  user: User;
}

export const updateUserRequestSchema: Schema<UpdateUserRequest> = object({
  user: ['user', lazy(() => userSchema)],
});
