/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  UserWithoutCreatorProfile1,
  userWithoutCreatorProfile1Schema,
} from './userWithoutCreatorProfile1';

export interface UserWithoutCreatorProfileResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: UserWithoutCreatorProfile1;
}

export const userWithoutCreatorProfileResponseSchema: Schema<UserWithoutCreatorProfileResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => userWithoutCreatorProfile1Schema)],
  }
);
