/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Pagination, paginationSchema } from './pagination';
import { User, userSchema } from './user';

export interface UsersResponse {
  status: string;
  message: string;
  data?: User[];
  pagination?: Pagination;
}

export const usersResponseSchema: Schema<UsersResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(array(lazy(() => userSchema)))],
  pagination: ['pagination', optional(lazy(() => paginationSchema))],
});
