/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  UserWithoutCreatorProfile,
  userWithoutCreatorProfileSchema,
} from './userWithoutCreatorProfile';

export interface UserWithoutCreatorProfileResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Represents a user in the system without creator profile. */
  data: UserWithoutCreatorProfile;
}

export const userWithoutCreatorProfileResponseSchema: Schema<UserWithoutCreatorProfileResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', lazy(() => userWithoutCreatorProfileSchema)],
  }
);
