/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

/** User information object */
export interface UserInfo {
  /** Unique identifier for the user */
  id?: string;
  /** User's email address */
  email?: string;
  /** User's username */
  userName?: string;
  /** The user's first name. */
  firstName?: string;
  /** The user's last name. */
  lastName?: string;
  /** Indicates if the user's email has been confirmed */
  emailConfirmed?: boolean;
  /** List of roles assigned to the user */
  roles?: string[];
  /** Timestamp of the user's last login */
  lastLoginAt?: string;
}

export const userInfoSchema: Schema<UserInfo> = object({
  id: ['id', optional(string())],
  email: ['email', optional(string())],
  userName: ['userName', optional(string())],
  firstName: ['firstName', optional(string())],
  lastName: ['lastName', optional(string())],
  emailConfirmed: ['emailConfirmed', optional(boolean())],
  roles: ['roles', optional(array(string()))],
  lastLoginAt: ['lastLoginAt', optional(string())],
});
