/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data7, data7Schema } from './data7';

export interface UsersResponse2 {
  status: string;
  message: string;
  data?: Data7;
}

export const usersResponse2Schema: Schema<UsersResponse2> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => data7Schema))],
});
