/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { User, userSchema } from './user';

export interface UserResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Represents a user in the system. */
  data: User;
}

export const userResponseSchema: Schema<UserResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => userSchema)],
});
