/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';

/** Represents a week within a training program. */
export interface Week {
  /** Unique identifier for the week. */
  weekId: number;
  /** Identifier of the user who created or owns this week. */
  userId: string;
  /** Title or name of the week. */
  weekTitle: string;
  /** JSON string containing the structured content of the week, including workout plans and notes. */
  weekContent: string;
  weekThumbnail?: MediaAsset;
  /** Timestamp of when the week was created. */
  createdAt: string;
  /** Timestamp of when the week was last updated. */
  updatedAt: string;
  /** Timestamp of when the week was soft deleted, if applicable. */
  deletedAt?: string;
  /** Identifier of the user who deleted the week, if applicable. */
  deletedBy?: string;
}

export const weekSchema: Schema<Week> = object({
  weekId: ['weekId', number()],
  userId: ['userId', string()],
  weekTitle: ['weekTitle', string()],
  weekContent: ['weekContent', string()],
  weekThumbnail: ['weekThumbnail', optional(lazy(() => mediaAssetSchema))],
  createdAt: ['createdAt', string()],
  updatedAt: ['updatedAt', string()],
  deletedAt: ['deletedAt', optional(string())],
  deletedBy: ['deletedBy', optional(string())],
});
