/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** Analytics data for the workout. */
export interface WorkoutAnalytics {
  /** Number of views for the workout. */
  views?: number;
  /** The number of times this workout has been used. */
  totalUses?: number;
  /** The average rating of the workout. */
  averageRating?: number;
}

export const workoutAnalyticsSchema: Schema<WorkoutAnalytics> = object({
  views: ['views', optional(number())],
  totalUses: ['totalUses', optional(number())],
  averageRating: ['averageRating', optional(number())],
});
