/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CreatorCredit, creatorCreditSchema } from './creatorCredit';

/** The data returned by the operation. */
export interface Workout1 {
  /** Unique identifier for the workout. */
  workoutId?: number;
  /** The title of the workout. */
  workoutTitle?: string;
  /** The date and time when the workout was last updated. */
  updatedAt?: string;
  /** The date and time when the workout was last used. */
  lastUsedAt?: string;
  /** The number of times this workout has been used. */
  totalUses?: number;
  /** The average rating of the workout. */
  averageRating?: number;
  /** List of creator credits associated with this workout. */
  creatorCredits?: CreatorCredit[];
}

export const workout1Schema: Schema<Workout1> = object({
  workoutId: ['workoutId', optional(number())],
  workoutTitle: ['workoutTitle', optional(string())],
  updatedAt: ['updatedAt', optional(string())],
  lastUsedAt: ['lastUsedAt', optional(string())],
  totalUses: ['totalUses', optional(number())],
  averageRating: ['averageRating', optional(number())],
  creatorCredits: [
    'creatorCredits',
    optional(array(lazy(() => creatorCreditSchema))),
  ],
});
