/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** Analytics data for the workout. */
export interface WorkoutAnalytics {
  /** Number of views for the workout. */
  totalViews?: number;
  /** The average rating of the workout. */
  ratingAverage?: number;
  /** The number of ratings for the workout. */
  ratingCount?: number;
}

export const workoutAnalyticsSchema: Schema<WorkoutAnalytics> = object({
  totalViews: ['totalViews', optional(number())],
  ratingAverage: ['ratingAverage', optional(number())],
  ratingCount: ['ratingCount', optional(number())],
});
