/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Workout1, workout1Schema } from './workout1';

export interface WorkoutResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: Workout1;
}

export const workoutResponseSchema: Schema<WorkoutResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => workout1Schema)],
});
