/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface WorkoutsDuplicateRequest {
  /** The title for the new duplicated workout */
  newWorkoutTitle: string;
}

export const workoutsDuplicateRequestSchema: Schema<WorkoutsDuplicateRequest> = object(
  { newWorkoutTitle: ['newWorkoutTitle', string()] }
);
