/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CreatorCredit, creatorCreditSchema } from './creatorCredit';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';
import { WorkoutAnalytics, workoutAnalyticsSchema } from './workoutAnalytics';
import { WorkoutSummary, workoutSummarySchema } from './workoutSummary';

/** Represents a workout in the system from the My Workouts Page. */
export interface WorkoutTableItem {
  /** Unique identifier for the workout. */
  workoutId?: string;
  /** ID of the original workout if this is a duplicate. */
  originalWorkoutId?: string;
  /** The title of the workout. */
  workoutTitle?: string;
  /** The URL slug of the workout. */
  workoutSlug?: string;
  workoutBackgroundImage?: MediaAsset;
  /** Indicates if the workout is a user's own workout or a bookmarked one from another user. */
  isBookmark?: boolean;
  /** List of creator credits associated with this workout. */
  creatorCredits?: CreatorCredit[];
  /** List of primary muscle group codes targeted in the workout. */
  primaryMuscleGroups?: string[];
  /** List of equipment codes used in the workout. */
  equipmentList?: string[];
  /** List of secondary muscles targeted in the workout. */
  secondaryMuscleGroups?: string[];
  /** The date and time when the workout was created. */
  createdAt?: string;
  /** The date and time when the workout was last updated. */
  updatedAt?: string;
  /** The date and time when the workout was last used. */
  lastViewedAt?: string;
  /** NOT IMPLEMENTED:- TODO- List of tags associated with the workout. */
  tags?: string[];
  /** Summary information about the workout. */
  workoutSummary?: WorkoutSummary;
  /** Analytics data for the workout. */
  workoutAnalytics?: WorkoutAnalytics;
}

export const workoutTableItemSchema: Schema<WorkoutTableItem> = object({
  workoutId: ['workoutId', optional(string())],
  originalWorkoutId: ['originalWorkoutId', optional(string())],
  workoutTitle: ['workoutTitle', optional(string())],
  workoutSlug: ['workoutSlug', optional(string())],
  workoutBackgroundImage: [
    'WorkoutBackgroundImage',
    optional(lazy(() => mediaAssetSchema)),
  ],
  isBookmark: ['isBookmark', optional(boolean())],
  creatorCredits: [
    'creatorCredits',
    optional(array(lazy(() => creatorCreditSchema))),
  ],
  primaryMuscleGroups: ['primaryMuscleGroups', optional(array(string()))],
  equipmentList: ['equipmentList', optional(array(string()))],
  secondaryMuscleGroups: ['secondaryMuscleGroups', optional(array(string()))],
  createdAt: ['createdAt', optional(string())],
  updatedAt: ['updatedAt', optional(string())],
  lastViewedAt: ['lastViewedAt', optional(string())],
  tags: ['tags', optional(array(string()))],
  workoutSummary: [
    'workoutSummary',
    optional(lazy(() => workoutSummarySchema)),
  ],
  workoutAnalytics: [
    'workoutAnalytics',
    optional(lazy(() => workoutAnalyticsSchema)),
  ],
});
