/**
 * Workout Creator APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Data96, data96Schema } from './data96';

export interface WorkoutsResponse1 {
  status: string;
  message: string;
  data?: Data96;
}

export const workoutsResponse1Schema: Schema<WorkoutsResponse1> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', optional(lazy(() => data96Schema))],
});
