/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { CreatorCredit, creatorCreditSchema } from './creatorCredit';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';
import { WorkoutAnalytics, workoutAnalyticsSchema } from './workoutAnalytics';
import { WorkoutContent, workoutContentSchema } from './workoutContent';
import { WorkoutData, workoutDataSchema } from './workoutData';
import {
  WorkoutEquipmentGroup,
  workoutEquipmentGroupSchema,
} from './workoutEquipmentGroup';
import {
  WorkoutMuscleGroupsPrimary,
  workoutMuscleGroupsPrimarySchema,
} from './workoutMuscleGroupsPrimary';
import {
  WorkoutMuscleGroupsSecondary,
  workoutMuscleGroupsSecondarySchema,
} from './workoutMuscleGroupsSecondary';
import { WorkoutSummary, workoutSummarySchema } from './workoutSummary';

/** Represents a workout in the system. */
export interface WorkoutPreview {
  /** Unique identifier for the workout. */
  workoutId?: string;
  /** The title of the workout. */
  workoutTitle?: string;
  workoutBackgroundImage?: MediaAsset;
  workoutMuscleGroupsPrimary?: WorkoutMuscleGroupsPrimary[];
  workoutMuscleGroupsSecondary?: WorkoutMuscleGroupsSecondary[];
  workoutEquipmentGroups?: WorkoutEquipmentGroup[];
  /** The date and time when the workout was last updated. */
  updatedAt?: string;
  /** The date and time when the workout was last used. */
  lastViewedAt?: string;
  workoutData?: WorkoutData[];
  workoutContent?: WorkoutContent;
  /** Summary information about the workout. */
  workoutSummary?: WorkoutSummary;
  /** Analytics data for the workout. */
  workoutAnalytics?: WorkoutAnalytics;
  /** List of creator credits associated with this workout. */
  creatorCredits?: CreatorCredit[];
}

export const workoutPreviewSchema: Schema<WorkoutPreview> = object({
  workoutId: ['workoutId', optional(string())],
  workoutTitle: ['workoutTitle', optional(string())],
  workoutBackgroundImage: [
    'workoutBackgroundImage',
    optional(lazy(() => mediaAssetSchema)),
  ],
  workoutMuscleGroupsPrimary: [
    'workoutMuscleGroupsPrimary',
    optional(array(lazy(() => workoutMuscleGroupsPrimarySchema))),
  ],
  workoutMuscleGroupsSecondary: [
    'workoutMuscleGroupsSecondary',
    optional(array(lazy(() => workoutMuscleGroupsSecondarySchema))),
  ],
  workoutEquipmentGroups: [
    'workoutEquipmentGroups',
    optional(array(lazy(() => workoutEquipmentGroupSchema))),
  ],
  updatedAt: ['updatedAt', optional(string())],
  lastViewedAt: ['lastViewedAt', optional(string())],
  workoutData: ['workoutData', optional(array(lazy(() => workoutDataSchema)))],
  workoutContent: [
    'workoutContent',
    optional(lazy(() => workoutContentSchema)),
  ],
  workoutSummary: [
    'workoutSummary',
    optional(lazy(() => workoutSummarySchema)),
  ],
  workoutAnalytics: [
    'workoutAnalytics',
    optional(lazy(() => workoutAnalyticsSchema)),
  ],
  creatorCredits: [
    'creatorCredits',
    optional(array(lazy(() => creatorCreditSchema))),
  ],
});
