/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Workout, workoutSchema } from './workout';

export interface WorkoutResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** Represents a workout in the system. */
  data: Workout;
}

export const workoutResponseSchema: Schema<WorkoutResponse> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => workoutSchema)],
});
