/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { MediaAsset, mediaAssetSchema } from './mediaAsset';

export interface WorkoutEquipmentGroup {
  /** Unique identifier for the equipment. */
  equipmentCode?: string;
  /** Name of the equipment, localized. */
  equipmentName?: string;
  equipmentThumbnail?: MediaAsset;
}

export const workoutEquipmentGroupSchema: Schema<WorkoutEquipmentGroup> = object(
  {
    equipmentCode: ['equipmentCode', optional(string())],
    equipmentName: ['equipmentName', optional(string())],
    equipmentThumbnail: [
      'equipmentThumbnail',
      optional(lazy(() => mediaAssetSchema)),
    ],
  }
);
