/**
 * JustGains-APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Pagination, paginationSchema } from './pagination';
import { WorkoutTableItem, workoutTableItemSchema } from './workoutTableItem';

export interface WorkoutTableListResponse {
  /** The status of the response, corresponding to standard HTTP status codes. */
  status: string;
  /** A human-readable message describing the result of the operation. */
  message: string;
  /** The data returned by the operation. */
  data: WorkoutTableItem[];
  pagination?: Pagination;
}

export const workoutTableListResponseSchema: Schema<WorkoutTableListResponse> = object(
  {
    status: ['status', string()],
    message: ['message', string()],
    data: ['data', array(lazy(() => workoutTableItemSchema))],
    pagination: ['pagination', optional(lazy(() => paginationSchema))],
  }
);
