name: Combine Markdown Files
on:
  push:
    branches:
      - '**'
permissions:
  contents: write
jobs:
  combine-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Find and combine markdown files
        run: |
          # Find all .md files (excluding those with LLM in the name) and combine them with separators
          find . -name "*.md" -type f ! -name "*LLM*.md" -print0 | while IFS= read -r -d '' file; do
            echo "Processing: $file"
            echo "# $file" >> temp_output.md
            echo "" >> temp_output.md
            cat "$file" >> temp_output.md
            echo "" >> temp_output.md
            echo "---" >> temp_output.md
            echo "" >> temp_output.md
          done
          
          echo "Debug - showing a few lines of temp_output.md:"
          head -n 20 temp_output.md
          
          # Keep the text inside brackets and remove the URL part
          # Using perl instead of sed for better regex support
          perl -pe 's/\[(.*?)\]\(.*?\)/[\1]/g' temp_output.md > LLM-Output.md
          
          echo "Debug - showing a few lines of processed LLM-Output.md:"
          head -n 20 LLM-Output.md
          
          rm temp_output.md
      - name: Commit combined file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LLM-Output.md
          git diff --staged --quiet || git commit -m "Update combined markdown file"
          git push
